import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const production = process.argv[2] === "production";
const cspSafePixi={
  name:"csp-safe-pixi",
  setup(build){
    const stubs=new Map([
      ["unsafeEvalSupported.mjs",'export function unsafeEvalSupported(){return false}'],
      ["generateParticleUpdateFunction.mjs",'export function generateParticleUpdateFunction(){throw new Error("PixiJS CSP polyfill was not installed")}'],
      ["GenerateShaderSyncCode.mjs",'export function generateShaderSyncCode(){throw new Error("PixiJS CSP polyfill was not installed")}'],
      ["createUboSyncFunction.mjs",'export function createUboSyncFunction(){throw new Error("PixiJS CSP polyfill was not installed")}'],
      ["generateUniformsSync.mjs",'export function generateUniformsSync(){throw new Error("PixiJS CSP polyfill was not installed")}'],
    ]);
    build.onLoad({filter:/pixi\.js[\\/]lib[\\/].*(?:unsafeEvalSupported|generateParticleUpdateFunction|GenerateShaderSyncCode|createUboSyncFunction|generateUniformsSync)\.mjs$/},args=>{
      const name=args.path.split(/[\\/]/).at(-1);
      const contents=name===undefined?undefined:stubs.get(name);
      if(contents===undefined)throw new Error(`Missing CSP-safe Pixi stub for ${args.path}`);
      return{contents,loader:"js"};
    });
  },
};
const shared={
  banner: {
    js: "/* Generated by esbuild. Source lives in src/. */",
  },
  bundle: true,
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  minify: production,
  plugins:[cspSafePixi],
};
const mainContext = await esbuild.context({...shared,
  entryPoints: ["src/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "node:*",
    ...builtinModules,
  ],
  format: "cjs",
  outfile: "main.js",
});

if (production) {
  await mainContext.rebuild();
  await mainContext.dispose();
} else {
  await mainContext.watch();
}
