import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const production = process.argv[2] === "production";
const shared={
  banner: {
    js: "/* Generated by esbuild. Source lives in src/. */",
  },
  bundle: true,
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  minify: production,
};
const mainContext = await esbuild.context({...shared,
  entryPoints: ["src/main.ts"],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "node:*",
    ...builtinModules,
  ],
  format: "cjs",
  outfile: "main.js",
});

if (production) {
  await mainContext.rebuild();
  await mainContext.dispose();
} else {
  await mainContext.watch();
}
