import test from "node:test";
import assert from "node:assert/strict";
import {LatestCoordinateResult,SharedCoordinateWriter,readSharedCoordinates} from "../src/coordinate-transport.ts";
import {createGraphWorkerRuntime} from "../src/worker-runtime.ts";
import {WORKER_PROTOCOL_VERSION,type GraphWorkerResponse} from "../src/worker-protocol.ts";

test("shared coordinate memory keeps identity until node capacity changes",()=>{const writer=new SharedCoordinateWriter();assert.equal(writer.ensureCapacity(2),true);const first=writer.publish(new Float32Array([1,2,3,4]));assert.equal(writer.ensureCapacity(2),false);const second=writer.publish(new Float32Array([5,6,7,8]));assert.equal(second.buffer,first.buffer);assert.equal(writer.ensureCapacity(3),true);const third=writer.publish(new Float32Array([1,2,3,4,5,6]));assert.notEqual(third.buffer,first.buffer)});

test("shared reader rejects incomplete, stale, and raced publications",()=>{const writer=new SharedCoordinateWriter();writer.ensureCapacity(2);const first=writer.publish(new Float32Array([1,2,3,4])),target=new Float32Array(4);assert.equal(readSharedCoordinates(first,target),true);assert.deepEqual([...target],[1,2,3,4]);const second=writer.publish(new Float32Array([5,6,7,8]));assert.equal(readSharedCoordinates(first,target),false);const version=new Int32Array(second.buffer,16,1);Atomics.add(version,0,1);assert.equal(readSharedCoordinates({...second,publication:second.publication+1},target),false);Atomics.add(version,0,1);const stable=writer.publish(new Float32Array([9,10,11,12]));assert.equal(readSharedCoordinates(stable,target,()=>{writer.publish(new Float32Array([13,14,15,16]))}),false)});

test("latest-result queue retains one unpublished result",()=>{const queue=new LatestCoordinateResult<number>();queue.push(1);queue.push(2);queue.push(3);assert.equal(queue.size,1);assert.equal(queue.take(),3);assert.equal(queue.size,0)});

test("worker shared publications reuse one buffer and send order only per topology revision",()=>{const messages:GraphWorkerResponse[]=[],timers:{callback:()=>void}[]=[];const runtime=createGraphWorkerRuntime({post:message=>messages.push(message),setTimer:callback=>{timers.push({callback});return timers.length},clearTimer:()=>{},supportsSharedMemory:()=>true});runtime.onMessage({type:"init",version:WORKER_PROTOCOL_VERSION,revision:1,nodes:[{id:"a",preserve:false,x:0,y:0,degree:0,radius:4}],edges:[],forces:{center:1,repel:1,link:.04,distance:50}});const first=messages.find(message=>message.type==="coordinates");assert.ok(first?.type==="coordinates"&&first.transport==="shared"&&first.buffer&&first.ids);timers.shift()!.callback();const second=messages.at(-1);assert.ok(second?.type==="coordinates"&&second.transport==="shared");if(first?.type==="coordinates"&&first.transport==="shared"&&second?.type==="coordinates"&&second.transport==="shared"){assert.equal(second.buffer,undefined);assert.equal(second.ids,undefined);assert.equal(second.count,first.count)}});

test("fallback transfers coordinate ownership without cloning",()=>{const received:GraphWorkerResponse[]=[],detached:number[]=[],runtime=createGraphWorkerRuntime({post:(message,transfer)=>{if(message.type==="coordinates"&&message.transport==="transfer"){const clone=structuredClone(message,{transfer:transfer??[]});detached.push(message.coords.byteLength);received.push(clone)}else received.push(message)},setTimer:()=>1,clearTimer:()=>{},supportsSharedMemory:()=>false});runtime.onMessage({type:"init",version:WORKER_PROTOCOL_VERSION,revision:1,nodes:[{id:"a",preserve:false,x:2,y:3,degree:0,radius:4}],edges:[],forces:{center:1,repel:1,link:.04,distance:50}});const coordinates=received.find(message=>message.type==="coordinates");assert.deepEqual(detached,[0]);assert.ok(coordinates?.type==="coordinates"&&coordinates.transport==="transfer");if(coordinates?.type==="coordinates"&&coordinates.transport==="transfer")assert.deepEqual([...coordinates.coords],[2,3])});
