import test from "node:test";
import assert from "node:assert/strict";
import { connectedFamilyAnchors, distributedFamilyAnchors, familySeedPosition, normalizeSeedEnvelope, positionSnapshot, prunePositionSnapshot, rankedPositionSnapshot, savedFamilyAnchors, savedLayoutStats } from "../src/layout-persistence.ts";

test("stale paths are pruned from exact position snapshots",()=>{const positions={a:{x:10,y:20},stale:{x:9000,y:9000},bad:{x:Number.NaN,y:0}},pruned=prunePositionSnapshot(positions,["a","bad"]);assert.deepEqual(pruned,{a:{x:10,y:20}});assert.deepEqual(positionSnapshot([{path:"a",x:1,y:2},{path:"bad",x:Infinity,y:0}]),{a:{x:1,y:2}})});
test("stale paths cannot influence saved span or centroid",()=>{const positions={a:{x:0,y:0},b:{x:100,y:40},stale:{x:10000,y:-10000}},stats=savedLayoutStats(positions,["a","b"]);assert.equal(stats.span,100);assert.deepEqual(stats.center,{x:50,y:20});assert.equal(stats.points.length,2)});
test("ranked snapshots retain the largest nodes with deterministic ties",()=>{const nodes=[{path:"small",x:1,y:1,radius:2,degree:9},{path:"z",x:2,y:2,radius:5,degree:1},{path:"a",x:3,y:3,radius:5,degree:1},{path:"hub",x:4,y:4,radius:5,degree:8}];assert.deepEqual(rankedPositionSnapshot(nodes,3),{hub:{x:4,y:4},a:{x:3,y:3},z:{x:2,y:2}});assert.deepEqual(rankedPositionSnapshot(nodes,0),{})});
test("unsaved nodes seed deterministically in bounded family-local sunflower rings",()=>{const anchors=savedFamilyAnchors([{path:"a",family:"one"},{path:"b",family:"one"},{path:"c",family:"two"}],{a:{x:0,y:10},b:{x:20,y:10}});assert.deepEqual(anchors.get("one"),{x:10,y:10});const first=familySeedPosition("new",4,"one",anchors,{x:100,y:100}),again=familySeedPosition("new",4,"one",anchors,{x:100,y:100}),next=familySeedPosition("newer",5,"one",anchors,{x:100,y:100}),fallback=familySeedPosition("other",4,"two",anchors,{x:100,y:100});assert.deepEqual(first,again);assert.notDeepEqual(first,next);assert.ok(Math.hypot(first.x-10,first.y-10)<40);assert.ok(Math.hypot(fallback.x-100,fallback.y-100)<40)});
test("partial-anchor seeds are distinct before physics begins",()=>{const anchors=new Map([["wiki",{x:0,y:0}]]),obstacles=[{x:0,y:0,radius:18}],points=[];for(let index=0;index<80;index++){const radius=6+(index%4),point=familySeedPosition(`wiki/${index}.md`,index,"wiki",anchors,{x:0,y:0},14,obstacles,radius);for(const obstacle of obstacles)assert.ok(Math.hypot(point.x-obstacle.x,point.y-obstacle.y)+1e-9>=radius+obstacle.radius);const placed={...point,radius};obstacles.push(placed);points.push(placed)}assert.equal(new Set(points.map(point=>`${point.x},${point.y}`)).size,points.length);assert.ok(points.every(point=>Math.hypot(point.x,point.y)<600))});
test("families without saved nodes receive deterministic separated anchors",()=>{const saved=new Map([["saved",{x:10,y:20}]]),first=distributedFamilyAnchors(["saved","alpha","beta","gamma"],saved,{x:0,y:0},1000),again=distributedFamilyAnchors(["gamma","alpha","saved","beta"],saved,{x:0,y:0},1000);assert.deepEqual(first,again);assert.deepEqual(first.get("saved"),{x:10,y:20});const missing=[first.get("alpha")!,first.get("beta")!,first.get("gamma")!];assert.ok(missing.every(point=>Math.hypot(point.x,point.y)>100&&Math.hypot(point.x,point.y)<=1600));for(let i=0;i<missing.length;i++)for(let j=i+1;j<missing.length;j++)assert.ok(Math.hypot(missing[i]!.x-missing[j]!.x,missing[i]!.y-missing[j]!.y)>100)});
test("unanchored families inherit the nearest connected saved-family anchor",()=>{const nodes=[{path:"saved/a",family:"saved"},{path:"bridge/a",family:"bridge"},{path:"remote/a",family:"remote"},{path:"isolated/a",family:"isolated"}],anchors=connectedFamilyAnchors(nodes,[{source:"saved/a",target:"bridge/a"},{source:"bridge/a",target:"remote/a"}],new Map([["saved",{x:40,y:-20}]]));assert.deepEqual(anchors.get("bridge"),{x:40,y:-20});assert.deepEqual(anchors.get("remote"),{x:40,y:-20});assert.equal(anchors.has("isolated"),false)});
test("seed envelope normalization preserves center while matching the topology span",()=>{const points=[{x:-1000,y:-500},{x:1000,y:500}],scale=normalizeSeedEnvelope(points,{x:0,y:0},1200);assert.equal(scale,.6);assert.deepEqual(points,[{x:-600,y:-300},{x:600,y:300}]);const stable=[{x:-550,y:0},{x:550,y:0}];assert.equal(normalizeSeedEnvelope(stable,{x:0,y:0},1200),1);assert.deepEqual(stable,[{x:-550,y:0},{x:550,y:0}])});
