import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source=readFileSync(new URL("../src/graph-view.ts",import.meta.url),"utf8"),styles=readFileSync(new URL("../styles.css",import.meta.url),"utf8");
test("forces are flat numeric rows with compact title-case labels",()=>{assert.doesNotMatch(source,/Advanced links/);assert.match(source,/"rootLinkForce","Root Force"/);assert.match(source,/"siblingLinkForce","Sibling Force"/);assert.match(source,/"link","Link Force"/);assert.match(source,/"distance","Link Distance"/);assert.match(source,/"curvature","Link Curve"/);assert.match(source,/"textFade","Text Fade"/);assert.match(source,/"linkThickness","Link Size"/);assert.match(source,/"glow","Glow"/)});
test("all preset panels expose the shared selector and Save Preset wording",()=>{assert.match(source,/beautiful-groups-presets-/);assert.match(source,/input\.setAttr\("list",id\)/);assert.doesNotMatch(source,/text:"Save"/);assert.ok((source.match(/text:"Save Preset"/g)??[]).length>=2);assert.doesNotMatch(styles,/grid-template-columns:1fr auto auto auto/)});
test("base pills and tethers are inside the blurred scene while focus copies stay crisp",()=>{assert.match(source,/this\.world\.addChild\(this\.territoryLayer,this\.links,this\.glowLayer,this\.nodeLayer,this\.leaderLayer,this\.labelLayer\)/);assert.match(source,/this\.focusWorld\.addChild\(this\.focusLinks,this\.focusGlowLayer,this\.focusNodeLayer,this\.focusLeaderLayer,this\.focusLabelLayer\)/)});
test("Groups bulk controls use the compact All Groups row",()=>{assert.match(source,/text:"All Groups"/);assert.match(source,/cls:"beautiful-groups-clear",text:"x"/);assert.doesNotMatch(source,/text:"Delete All Groups"/);assert.doesNotMatch(source,/text:"Show on graph"/)});
test("panel buttons share compact typography and auto-height geometry remains enabled",()=>{assert.match(styles,/\.beautiful-graph-panel button\{[^}]*font-size:11px/);assert.match(styles,/\.beautiful-panel-forces\{height:321px\}/);assert.match(source,/state\.autoHeight!==false\?"auto"/)});
test("zoom presentation reuses cached metrics, bounds collision solves, and interpolates every frame",()=>{assert.match(source,/if\(view\.labelMetrics\)return view\.labelMetrics/);assert.match(source,/interval=this\.zoomAnimating\?72:100/);assert.match(source,/this\.advanceLabelOffsets\(deltaMS\)/);assert.doesNotMatch(source,/!this\.zoomAnimating&&\(this\.labelLayoutDirty\|\|now<this\.motionUntil\)/)});
test("compact controls preserve circular swatches and shared preset proportions",()=>{assert.match(styles,/\.beautiful-group-swatch\{[^}]*height:10px!important;min-height:10px!important/);assert.match(styles,/grid-template-columns:minmax\(0,1fr\) minmax\(0,1\.5fr\) minmax\(0,1fr\)/);assert.doesNotMatch(styles,/\.beautiful-panel-groups \.beautiful-preset-row\{grid-template-columns:1fr 1fr 1fr\}/)});
test("requested controls and persistence repairs remain wired",()=>{assert.match(source,/text:"Recenter Graph"/);assert.match(source,/"Show Orphans"/);assert.match(source,/"Center Focused Node"/);assert.match(source,/"Everything Else"/);assert.match(source,/width:4\/this\.scale/);assert.match(styles,/\.beautiful-graph-toolbar\{bottom:3%\}/);assert.match(styles,/\.beautiful-root-toggle\{[^}]*min-height:15px!important;[^}]*aspect-ratio:1/)});
test("startup uses one explicit lifecycle and preserves panel state",()=>{assert.match(source,/type StartupPhase="waiting"\|"building"\|"settling"\|"complete"\|"cancelled"/);assert.doesNotMatch(source,/startupPending|startupVisible|startupTimer/);assert.doesNotMatch(source,/metadataCache\.on\("resolved"/);const main=readFileSync(new URL("../src/main.ts",import.meta.url),"utf8");assert.doesNotMatch(main,/state\.collapsed&&id==="forces"/)});
test("startup finalization drains presentation and camera residuals without a terminal fit",()=>{assert.match(source,/const deadline=performance\.now\(\)\+150/);assert.match(source,/presentationTargetDelta\(\)/);assert.match(source,/startupCameraResidual\(\)/);assert.match(source,/ordinaryLabel=this\.startupPhase==="complete"/);assert.doesNotMatch(source,/if\(!wasVisible\)this\.fit\(\)/);assert.doesNotMatch(source,/finishPhysicsLayout\([^)]*recenter/)});
test("camera animation refreshes icon threshold presentation every frame",()=>{assert.match(source,/if\(view\.icon\)this\.updateIconPresentation\(view,related\)/);assert.match(source,/icon\.scale\.set\(\.05\+\.95\*fade\)/)});
test("saved anchor setting spans five through one hundred",()=>{const settings=readFileSync(new URL("../src/settings.ts",import.meta.url),"utf8");assert.match(settings,/setLimits\(5,100,5\)/)});
