import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source=readFileSync(new URL("../src/graph-view.ts",import.meta.url),"utf8"),styles=readFileSync(new URL("../styles.css",import.meta.url),"utf8");
test("forces are flat numeric rows with compact labels",()=>{assert.doesNotMatch(source,/Advanced links/);assert.match(source,/"rootLinkForce","Root force"/);assert.match(source,/"siblingLinkForce","Sibling force"/);assert.match(source,/"link","Link force"/);assert.match(source,/"distance","Link distance"/);assert.match(source,/"curvature","Link curve"/);assert.match(source,/"textFade","Text fade"/);assert.match(source,/"linkThickness","Link size"/);assert.match(source,/"glow","Glow amount"/)});
test("all preset panels expose the shared selector and Save preset wording",()=>{assert.match(source,/beautiful-groups-presets-/);assert.match(source,/input\.setAttr\("list",id\)/);assert.doesNotMatch(source,/text:"Save"/);assert.ok((source.match(/text:"Save preset"/g)??[]).length>=2);assert.doesNotMatch(styles,/grid-template-columns:1fr auto auto auto/)});
test("base pills and tethers are inside the blurred scene while focus copies stay crisp",()=>{assert.match(source,/this\.world\.addChild\(this\.territoryLayer,this\.links,this\.glowLayer,this\.nodeLayer,this\.leaderLayer,this\.labelLayer\)/);assert.match(source,/this\.focusWorld\.addChild\(this\.focusLinks,this\.focusGlowLayer,this\.focusNodeLayer,this\.focusLeaderLayer,this\.focusLabelLayer\)/)});
test("Groups bulk controls use the compact All Groups row",()=>{assert.match(source,/text:"All Groups"/);assert.match(source,/cls:"beautiful-groups-clear",text:"x"/);assert.doesNotMatch(source,/text:"Delete All Groups"/);assert.doesNotMatch(source,/text:"Show on graph"/)});
test("panel buttons share compact typography and auto-height geometry remains enabled",()=>{assert.match(styles,/\.beautiful-graph-panel button\{[^}]*font-size:11px/);assert.match(styles,/\.beautiful-panel-forces\{height:321px\}/);assert.match(source,/state\.autoHeight!==false\?"auto"/)});
test("zoom presentation reuses cached pill metrics and defers collision layout",()=>{assert.match(source,/if\(view\.labelMetrics\)return view\.labelMetrics/);assert.match(source,/!this\.zoomAnimating&&\(this\.labelLayoutDirty\|\|now<this\.motionUntil\)/);assert.doesNotMatch(source,/lastCameraPresentation<80/)});
test("compact controls preserve circular swatches and shared preset proportions",()=>{assert.match(styles,/\.beautiful-group-swatch\{[^}]*height:10px!important;min-height:10px!important/);assert.match(styles,/grid-template-columns:minmax\(0,1fr\) minmax\(0,1\.5fr\) minmax\(0,1fr\)/);assert.doesNotMatch(styles,/\.beautiful-panel-groups \.beautiful-preset-row\{grid-template-columns:1fr 1fr 1fr\}/)});
