import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {circleIntersectsViewport,MAX_NODE_VIEWS_PER_FRAME,nearestMissing,reconcilePersistentObjects,RenderIdleWindow,RENDER_IDLE_FRAME_LIMIT,segmentIntersectsViewport,worldViewport} from "../src/renderer-lifecycle.ts";

test("lazy node admission is capped at fifty and ordered from the viewport center",()=>{const nodes=Array.from({length:80},(_,index)=>({id:`n${index}`,x:index-40,y:0})),present=new Set(["n40"]),batch=nearestMissing(nodes,present,{x:0,y:0});assert.equal(MAX_NODE_VIEWS_PER_FRAME,50);assert.equal(batch.length,50);assert.deepEqual(batch.slice(0,4).map(node=>node.id),["n39","n41","n38","n42"])});
test("render idle window includes the audited sixty-frame tail and wakes again",()=>{const idle=new RenderIdleWindow();assert.equal(idle.nextFrame(),false);idle.changed();for(let frame=0;frame<=RENDER_IDLE_FRAME_LIMIT;frame++)assert.equal(idle.nextFrame(),true);assert.equal(idle.nextFrame(),false);idle.changed();assert.equal(idle.nextFrame(),true)});
test("viewport helpers apply margins and reject offscreen link geometry",()=>{const viewport=worldViewport(800,600,2,{x:400,y:300},20);assert.deepEqual(viewport,{minX:-210,maxX:210,minY:-160,maxY:160});assert.equal(circleIntersectsViewport(220,0,12,viewport),true);assert.equal(circleIntersectsViewport(240,0,12,viewport),false);assert.equal(segmentIntersectsViewport({x:-300,y:0},{x:300,y:0},viewport),true);assert.equal(segmentIntersectsViewport({x:-300,y:190},{x:300,y:190},viewport),false)});
test("persistent objects retain identity and removed objects are destroyed exactly once",()=>{const first={id:"a"},removed={id:"gone"},objects=new Map([["a",first],["gone",removed]]),destroyed:object[]=[];reconcilePersistentObjects(new Set(["a","b"]),objects,id=>({id}),value=>destroyed.push(value));assert.equal(objects.get("a"),first);assert.equal(objects.get("b")?.id,"b");assert.deepEqual(destroyed,[removed]);reconcilePersistentObjects(new Set(["a","b"]),objects,id=>({id}),value=>destroyed.push(value));assert.deepEqual(destroyed,[removed])});
test("Pixi lifecycle disables automatic animation and owns exact object destruction",()=>{const source=readFileSync(new URL("../src/graph-view.ts",import.meta.url),"utf8");assert.match(source,/autoStart:false,sharedTicker:false/);assert.match(source,/private changed\(dirty=PresentationDirty\.All\):void/);assert.match(source,/new RenderIdleWindow\(\)/);assert.match(source,/private destroyEdgeView[\s\S]*line\.destroy\(\)[\s\S]*focus\.destroy\(\)/);assert.match(source,/private destroyNodeView[\s\S]*child\?\.destroy\(\)/);assert.doesNotMatch(source,/pixi\.ticker\.add/)});

test("persistent links use shared white sprites compatible with Pixi batching",()=>{const source=readFileSync(new URL("../src/graph-view.ts",import.meta.url),"utf8");assert.match(source,/line=new Sprite\(Texture\.WHITE\),focus=new Sprite\(Texture\.WHITE\)/);assert.match(source,/sprite\.tint=color;sprite\.alpha=alpha/);assert.doesNotMatch(source,/view\.line\.clear\(|view\.graphics\.clear\(/)});
test("startup metrics instrument the bounded lazy batches and one seed fit",()=>{const source=readFileSync(new URL("../src/graph-view.ts",import.meta.url),"utf8");assert.match(source,/maxNodeBatch\?:number/);assert.match(source,/initialCameraOccupancy\?:number/);assert.match(source,/nearestMissing\(this\.model\.nodes,present,center,MAX_NODE_VIEWS_PER_FRAME\)/);assert.match(source,/maxNodeBatch=Math\.max/);assert.match(source,/firstEdgeCount=this\.edgeViews\.size/);assert.match(source,/initialCameraOccupancy=Math\.max/)});
test("steady frames reuse topology indexes and skip edge admission",()=>{const source=readFileSync(new URL("../src/graph-view.ts",import.meta.url),"utf8");assert.match(source,/private edgeIndex = new Map/);assert.match(source,/if\(batch\.length\)this\.admitEdgeViews\(\)/);assert.match(source,/const edge=this\.edgeIndex\.get\(key\)/);assert.doesNotMatch(source,/const visible = new Map\(this\.model\.nodes\.filter/)});
