import assert from "node:assert/strict";
import test from "node:test";
import { admitStartup, metadataGraphReady } from "../src/startup-admission.ts";
import { prepareWorkerTopology, reconcileGraphNodes, sameWorkerTopology } from "../src/graph-reconcile.ts";
import type { GraphNode } from "../src/types.ts";
import { readFileSync } from "node:fs";

const node=(id:string,x:number,y:number,label=id)=>({id,path:id,label,folder:"",category:"",color:"#ffffff",icon:"",degree:1,baseRadius:4,radius:4,description:"",visible:true,hub:false,alwaysLabel:false,rootIndexStyled:false,family:"root",x,y}) satisfies GraphNode;

test("restored startup waits for layout and metadata readiness and begins exactly once",()=>{let layoutReady:(()=>void)|undefined,metadataReady:(()=>void)|undefined,begins=0;admitStartup(false,next=>{layoutReady=next},false,next=>{metadataReady=next},()=>begins++);assert.equal(begins,0);layoutReady!();assert.equal(begins,0);metadataReady!();metadataReady!();assert.equal(begins,1)});
test("manual open begins immediately when layout and metadata are ready",()=>{let layoutRegistered=false,metadataRegistered=false,begins=0;admitStartup(true,()=>{layoutRegistered=true},true,()=>{metadataRegistered=true},()=>begins++);assert.equal(layoutRegistered,false);assert.equal(metadataRegistered,false);assert.equal(begins,1)});
test("closing before readiness cancels pending startup work",()=>{let layoutReady:(()=>void)|undefined,metadataReady:(()=>void)|undefined,begins=0;const cancel=admitStartup(false,next=>{layoutReady=next},false,next=>{metadataReady=next},()=>begins++);cancel();layoutReady!();metadataReady!();assert.equal(begins,0)});
test("metadata readiness requires link-resolution coverage for every markdown source",()=>{const resolved={"wiki/index.md":{"index.md":1}},unresolved={"empty.md":{}};assert.equal(metadataGraphReady(["wiki/index.md","empty.md"],resolved,unresolved),true);assert.equal(metadataGraphReady(["wiki/index.md","missing.md"],resolved,unresolved),false)});
test("topology reconciliation preserves unchanged identity and transient coordinates",()=>{const keep=node("keep.md",10,20,"old"),remove=node("remove.md",30,40),freshKeep=node("keep.md",900,800,"new"),added=node("added.md",50,60),result=reconcileGraphNodes([keep,remove],[freshKeep,added]);assert.equal(result.nodes[0],keep);assert.deepEqual({x:keep.x,y:keep.y,label:keep.label},{x:10,y:20,label:"new"});assert.deepEqual([...result.removedIds],["remove.md"]);assert.deepEqual(result.added,[added])});
test("worker topology preserves survivors and seeds linked additions near positioned neighbors",()=>{const keep=node("keep.md",100,50),added=node("added.md",0,0),edge={source:"keep.md",target:"added.md",forward:true,reverse:false,relationship:"cross" as const},random=[.5,.5][Symbol.iterator](),result=prepareWorkerTopology([keep,added],[edge],new Set(["keep.md"]),{},()=>random.next().value??.5);assert.deepEqual(result.nodes[0],{id:"keep.md",preserve:true,degree:1,radius:4});assert.deepEqual(result.nodes[1],{id:"added.md",preserve:false,x:100,y:50,degree:1,radius:4});assert.equal(added.degree,1)});
test("unlinked additions use the audited outer-area expansion",()=>{const keep=node("keep.md",30,40),added=node("added.md",0,0),result=prepareWorkerTopology([keep,added],[],new Set(["keep.md"]),{},()=>0);assert.equal(result.nodes[1]?.x,Math.sqrt(50*50+3600));assert.equal(result.nodes[1]?.y,0);assert.equal(result.nodes[1]?.degree,0)});
test("stored coordinates are soft startup seeds and nonstored neighbors use them",()=>{const stored=node("stored.md",0,0),added=node("added.md",0,0),edge={source:"stored.md",target:"added.md",forward:true,reverse:false,relationship:"cross" as const},result=prepareWorkerTopology([stored,added],[edge],new Set(),{"stored.md":{x:20,y:-10}},()=>.5);assert.deepEqual(result.nodes[0],{id:"stored.md",preserve:false,x:20,y:-10,degree:1,radius:4});assert.deepEqual(result.nodes[1],{id:"added.md",preserve:false,x:20,y:-10,degree:1,radius:4});assert.equal("fx" in result.nodes[0]!,false)});
test("family labels do not influence audited placement",()=>{const left=node("a",0,0),right=node("b",0,0),edge={source:"a",target:"b",forward:true,reverse:false,relationship:"cross" as const};left.family="one";right.family="two";const first=prepareWorkerTopology([left,right],[edge],new Set(),{},()=>.25).nodes.map(item=>({x:item.x,y:item.y}));left.x=0;left.y=0;right.x=0;right.y=0;left.family="shared";right.family="shared";const second=prepareWorkerTopology([left,right],[edge],new Set(),{},()=>.25).nodes.map(item=>({x:item.x,y:item.y}));assert.deepEqual(first,second)});
test("display relationship changes bypass worker topology but radius and visibility changes do not",()=>{const first=node("a",0,0),second=node("b",0,0),edge={source:"a",target:"b",forward:true,reverse:false,relationship:"parent" as const};assert.equal(sameWorkerTopology([first,second],[edge],[{...first,label:"new"},{...second}],[{...edge,relationship:"sibling"}]),true);assert.equal(sameWorkerTopology([first,second],[edge],[{...first,radius:9},{...second}],[edge]),false);assert.equal(sameWorkerTopology([first,second],[edge],[{...first,visible:false},{...second}],[edge]),false)});
const viewSource=readFileSync(new URL("../src/graph-view.ts",import.meta.url),"utf8");
test("prepared scene is rendered before reveal and physics starts after first paint",()=>{const prepared=viewSource.indexOf('this.setStartupPhase("prepared")'),revealed=viewSource.indexOf('this.setStartupPhase("settling")'),painted=viewSource.indexOf("this.startupMetrics.firstPaintAt=performance.now()"),worker=viewSource.indexOf("this.startActiveWorker(true,{heat:1,startup:true})",painted);assert.ok(prepared>0&&prepared<revealed);assert.ok(revealed<painted&&painted<worker);assert.match(viewSource,/renderer\.render\(this\.pixi\.stage\)/)});
test("startup seeds the complete active model before its one initial fit",()=>{const seeded=viewSource.indexOf("this.preparedInitialTopology=prepareWorkerTopology"),fit=viewSource.indexOf("this.fit(false)",seeded),lazy=viewSource.indexOf("this.populateScene()",fit);assert.ok(seeded>0&&seeded<fit&&fit<lazy);assert.doesNotMatch(viewSource,/trackStartupCamera|startupCameraTracking/)});
test("startup yields after model and topology preparation before scene work",()=>{assert.match(viewSource,/modelCompleteAt=performance\.now\(\);this\.startupMetrics\.finalNodeCount=model\.nodes\.length;await new Promise<void>\(resolve=>requestAnimationFrame/);assert.match(viewSource,/this\.preparedInitialTopology=prepareWorkerTopology[\s\S]*?await new Promise<void>\(resolve=>requestAnimationFrame/)});
test("startup completes from worker sleep without an equilibrium deadline",()=>{const runtimeSource=readFileSync(new URL("../src/worker-runtime.ts",import.meta.url),"utf8"),initial=viewSource.match(/private finishInitialLayout[\s\S]*?\n\s*private recordTerminalMetrics/)?.[0]??"";assert.match(runtimeSource,/publish\("sleep"\)/);assert.doesNotMatch(runtimeSource,/deadline|maxSubsteps|burstComplete/);assert.doesNotMatch(viewSource,/equilibrium deadline/);assert.match(initial,/this\.completeStartup\(metrics\)/);assert.doesNotMatch(initial,/degradeStartup|deadline/)});
test("stored snapshots update when a pending sleep result is consumed and hot close does not overwrite them",()=>{const close=viewSource.match(/async onClose\(\)[\s\S]*?\n\s*private setStartupPhase/)?.[0]??"",consume=viewSource.match(/private consumeCoordinateResult[\s\S]*?\n\s*private renderOnDemand/)?.[0]??"";assert.match(consume,/message\.type==="sleep"[\s\S]*saveCooledPositions/);assert.doesNotMatch(close,/saveCooledPositions|rankedPositionSnapshot|data\.positions/)});
test("moving edges update persistent endpoint-gated straight graphics",()=>{assert.match(viewSource,/this\.views\.has\(edge\.source\)&&this\.views\.has\(edge\.target\)/);assert.match(viewSource,/reconcilePersistentObjects\(wanted,this\.edgeViews/);assert.match(viewSource,/segmentIntersectsViewport/);assert.match(viewSource,/\.moveTo\(a\.x,a\.y\)\.lineTo\(b\.x,b\.y\)/);assert.doesNotMatch(viewSource,/edgeBuckets|edgeBend|quadraticCurveTo\(\(a\.x\+b\.x\)/)});
