import assert from "node:assert/strict";
import test from "node:test";
import { admitStartup, metadataGraphReady } from "../src/startup-admission.ts";
import { reconcileGraphNodes } from "../src/graph-reconcile.ts";
import type { GraphNode } from "../src/types.ts";
import { readFileSync } from "node:fs";

const node=(id:string,x:number,y:number,label=id)=>({id,path:id,label,folder:"",category:"",color:"#ffffff",icon:"",degree:1,baseRadius:4,radius:4,description:"",visible:true,hub:false,alwaysLabel:false,rootIndexStyled:false,family:"root",x,y}) satisfies GraphNode;

test("restored startup waits for layout and metadata readiness and begins exactly once",()=>{let layoutReady:(()=>void)|undefined,metadataReady:(()=>void)|undefined,begins=0;admitStartup(false,next=>{layoutReady=next},false,next=>{metadataReady=next},()=>begins++);assert.equal(begins,0);layoutReady!();assert.equal(begins,0);metadataReady!();metadataReady!();assert.equal(begins,1)});
test("manual open begins immediately when layout and metadata are ready",()=>{let layoutRegistered=false,metadataRegistered=false,begins=0;admitStartup(true,()=>{layoutRegistered=true},true,()=>{metadataRegistered=true},()=>begins++);assert.equal(layoutRegistered,false);assert.equal(metadataRegistered,false);assert.equal(begins,1)});
test("closing before readiness cancels pending startup work",()=>{let layoutReady:(()=>void)|undefined,metadataReady:(()=>void)|undefined,begins=0;const cancel=admitStartup(false,next=>{layoutReady=next},false,next=>{metadataReady=next},()=>begins++);cancel();layoutReady!();metadataReady!();assert.equal(begins,0)});
test("metadata readiness requires link-resolution coverage for every markdown source",()=>{const resolved={"wiki/index.md":{"index.md":1}},unresolved={"empty.md":{}};assert.equal(metadataGraphReady(["wiki/index.md","empty.md"],resolved,unresolved),true);assert.equal(metadataGraphReady(["wiki/index.md","missing.md"],resolved,unresolved),false)});
test("topology reconciliation preserves unchanged identity and transient coordinates",()=>{const keep=node("keep.md",10,20,"old"),remove=node("remove.md",30,40),freshKeep=node("keep.md",900,800,"new"),added=node("added.md",50,60),result=reconcileGraphNodes([keep,remove],[freshKeep,added]);assert.equal(result.nodes[0],keep);assert.deepEqual({x:keep.x,y:keep.y,label:keep.label},{x:10,y:20,label:"new"});assert.deepEqual([...result.removedIds],["remove.md"]);assert.deepEqual(result.added,[added])});
const viewSource=readFileSync(new URL("../src/graph-view.ts",import.meta.url),"utf8");
test("prepared scene is rendered before reveal and physics starts after first paint",()=>{const prepared=viewSource.indexOf('this.setStartupPhase("prepared")'),revealed=viewSource.indexOf('this.setStartupPhase("settling")'),painted=viewSource.indexOf("this.startupMetrics.firstPaintAt=performance.now()"),worker=viewSource.indexOf("this.startActiveWorker(true,{heat:1,startup:true})",painted);assert.ok(prepared>0&&prepared<revealed);assert.ok(revealed<painted&&painted<worker);assert.match(viewSource,/renderer\.render\(this\.pixi\.stage\)/)});
test("startup completes from worker sleep without an equilibrium deadline",()=>{const runtimeSource=readFileSync(new URL("../src/worker-runtime.ts",import.meta.url),"utf8"),initial=viewSource.match(/private finishInitialLayout[\s\S]*?\n\s*private recordTerminalMetrics/)?.[0]??"";assert.match(runtimeSource,/publish\("sleep"\)/);assert.doesNotMatch(runtimeSource,/deadline|maxSubsteps|burstComplete/);assert.doesNotMatch(viewSource,/equilibrium deadline/);assert.match(initial,/this\.completeStartup\(metrics\)/);assert.doesNotMatch(initial,/degradeStartup|deadline/)});
test("moving edges are emitted through cached style buckets",()=>{assert.match(viewSource,/edgeBuckets=new Map/);assert.match(viewSource,/bucket\.segments\.push/);assert.match(viewSource,/this\.edgeRenderBuckets=\[\.\.\.edgeBuckets\.values\(\)\]/);assert.match(viewSource,/for\(const bucket of this\.edgeRenderBuckets\)/)});
