import { ItemView, Menu, Notice, TFile, TFolder, WorkspaceLeaf } from "obsidian";
import { Application, BlurFilter, Container, Graphics, Sprite, Text, TextStyle, Texture } from "pixi.js";
import { buildGraphModel } from "./graph-model";
import { createPhysicsWorker } from "./physics-worker";
import type BeautifulGraphPlugin from "./main";
import type { BeautifulGraphSettings, GraphModel, GraphNode } from "./types";
import { DEFAULT_DISPLAY, DEFAULT_FORCES } from "./defaults";
import { folderDisplayName, isPathInFolder, isPathInFolderScope, unionLensMembership } from "./folder-lens";
import { formatTooltipPath } from "./format-label";
import { buildLensContours } from "./lens-contour";
import { defaultGroupIcon, displayDirectory, effectiveGroup, GROUP_PALETTES, inferGroups, nodeAllowed, normalizeIcon } from "./groups";
import { activeNodeIds, applyDerivedNodePresentation, sameNodeIds } from "./node-presentation";

export const BEAUTIFUL_GRAPH_VIEW = "beautiful-graph";
type NodeView = { node: GraphNode; body: Graphics; surface: Sprite; glow: Sprite; icon?: Text; iconRes?: number; label?: Text; labelBg?: Graphics; leader?:Graphics; styleKey?: string };
export class BeautifulGraphView extends ItemView {
  private pixi?: Application;
  private scene = new Container();
  private world = new Container();
  private territoryLayer = new Container();
  private focusWorld = new Container();
  private focusLinks = new Graphics();
  private focusGlowLayer = new Container();
  private focusNodeLayer = new Container();
  private focusLabelLayer = new Container();
  private links = new Graphics();
  private glowLayer = new Container();
  private nodeLayer = new Container();
  private labelLayer = new Container();
  private model: GraphModel = { nodes: [], edges: [] };
  private views = new Map<string, NodeView>();
  private adjacency = new Map<string, Set<string>>();
  private worker?: Worker;
  private workerNodeIds = new Set<string>();
  private scale = 1;
  private offset = { x: 0, y: 0 };
  private hovered?: GraphNode;
  private search = "";
  private renderQueued = false;
  private lastFrame = 0;
  private initialFitPending = true;
  private dragged?: GraphNode;
  private physicsTicks = 0;
  private visibility = new Map<string, number>();
  private zoomTarget?: { scale:number; x:number; y:number };
  private zoomAnimating = false;
  private edgeBends = new Map<string, number>();
  private glowTexture?: Texture;
  private focusProgress = 0;
  private focusAnimation = 0;
  private focusTarget = 0;
  private focusPinned = false;
  private focusBlur = new BlurFilter({ strength: 0, quality: 1 });
  private minRadius = 1;
  private maxRadius = 1;
  private history: BeautifulGraphSettings[] = [];
  private physicsTargets = new Map<string,{x:number;y:number}>();
  private motionUntil = 0;
  private lastBendUpdate = 0;
  private lastGeometryRender = 0;
  private modelRefreshTimer?: number;
  private presetOverwriteArmed = new Map<string, number>();
  private nodeTextures = new Map<string, Texture>();
  private labelOffsets = new Map<string,{x:number;y:number;side:1|-1}>();
  private hoverTimer?: number;
  private hoverCandidate?: string;
  private folderScope = "";
  private lensShapes = new Map<string,Graphics>();
  private activeLenses = new Set<string>();
  private lensMembers = new Set<string>();
  private lastTerritoryUpdate = 0;
  private lensGeometryDirty = true;
  private folderTapTimers = new Map<string,number>();
  private scopeHistory: {scope:string;scale:number;offset:{x:number;y:number}}[] = [];
  private initialFitTimer?: number;
  private searchTimer?: number;
  private searchGeneration=0;
  private searchRoles=new Map<string,"match"|"context"|"hidden">();
  private searchIndex=new Map<string,string>();
  private searchInput?:HTMLInputElement;
  private visibilityAnimation=0;
  private lensDiagnosticSignature="";
  private panelZ=20;

  constructor(leaf: WorkspaceLeaf, private plugin: BeautifulGraphPlugin) { super(leaf); }
  getViewType(): string { return BEAUTIFUL_GRAPH_VIEW; }
  getDisplayText(): string { return "Beautiful Graph"; }
  getIcon(): string { return "orbit"; }

  async onOpen(): Promise<void> {
    this.contentEl.empty();
    this.plugin.registerGraph(this);
    this.contentEl.addClass("beautiful-graph-view");
    const canvasHost = this.contentEl.createDiv({ cls: "beautiful-graph-canvas" });
    this.pixi = new Application();
    await this.pixi.init({ resizeTo: canvasHost, antialias: true, backgroundAlpha: 0, preference: "webgl" });
    this.pixi.ticker.add(ticker=>this.animatePresentation(ticker.deltaMS));
    const syncTicker=()=>{const active=document.hasFocus()&&this.app.workspace.getActiveViewOfType(BeautifulGraphView)===this;if(active)this.pixi?.ticker.start();else this.pixi?.ticker.stop()};
    this.registerEvent(this.app.workspace.on("active-leaf-change",syncTicker));
    this.registerDomEvent(window,"focus",syncTicker);this.registerDomEvent(window,"blur",()=>{this.cancelHoverIntent();this.clearHover();syncTicker()});
    this.registerEvent(this.app.metadataCache.on("changed",()=>this.scheduleModelRefresh()));
    this.registerEvent(this.app.metadataCache.on("resolved",()=>this.scheduleModelRefresh()));
    this.registerEvent(this.app.vault.on("create",()=>this.scheduleModelRefresh()));
    this.registerEvent(this.app.vault.on("delete",()=>this.scheduleModelRefresh()));
    this.registerEvent(this.app.vault.on("rename",()=>this.scheduleModelRefresh()));
    this.registerDomEvent(window,"keydown",e=>{const target=e.target as HTMLElement|null,isEditor=target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement,isControl=isEditor||target instanceof HTMLButtonElement;if(!document.hasFocus()||this.app.workspace.getActiveViewOfType(BeautifulGraphView)!==this)return;if(e.code==="Space"&&target===this.searchInput&&!this.searchInput.value.length&&!e.ctrlKey&&!e.altKey&&!e.metaKey){e.preventDefault();e.stopPropagation();this.fit();return}if(e.ctrlKey&&!e.shiftKey&&e.key.toLowerCase()==="z"&&!isEditor){e.preventDefault();e.stopPropagation();this.undoSettings();return}if(e.code==="Space"&&!e.ctrlKey&&!e.altKey&&!e.metaKey&&!isControl){e.preventDefault();e.stopPropagation();this.fit();return}if(!isEditor&&!e.ctrlKey&&!e.altKey&&!e.metaKey&&e.key.length===1){this.searchInput?.focus();this.searchInput?.setSelectionRange(this.searchInput.value.length,this.searchInput.value.length)}});
    this.registerDomEvent(this.contentEl,"pointerdown",event=>{const target=event.target as HTMLElement|null;if(target instanceof HTMLInputElement||target instanceof HTMLTextAreaElement||target instanceof HTMLSelectElement)return;window.setTimeout(()=>this.searchInput?.focus({preventScroll:true}),0)});
    canvasHost.appendChild(this.pixi.canvas);
    this.glowTexture=this.createGlowTexture();
    this.world.addChild(this.territoryLayer,this.links,this.glowLayer,this.nodeLayer,this.labelLayer);
    this.focusWorld.addChild(this.focusLinks,this.focusGlowLayer,this.focusNodeLayer,this.focusLabelLayer);
    this.scene.addChild(this.world);this.pixi.stage.addChild(this.scene,this.focusWorld);
    this.folderScope="";
    this.model = buildGraphModel(this.app, this.plugin.settings, this.plugin.data.positions);
    if(this.folderScope&&!this.model.nodes.some(node=>isPathInFolderScope(node.path,this.folderScope)))this.folderScope="";
    this.applyScopeFlags();
    this.applyAnalyzedForceProfile();
    this.createToolbar();
    this.updateBreadcrumb();
    const toolbar=this.contentEl.querySelector<HTMLElement>(".beautiful-graph-toolbar");if(toolbar){const undo=toolbar.createEl("button",{text:"Undo",attr:{"aria-label":"Undo graph settings (Ctrl+Z)"}});undo.onclick=()=>this.undoSettings();toolbar.insertBefore(undo,toolbar.lastElementChild)}
    this.createPanels();
    this.createGuiDock();
    this.bindNavigation(canvasHost);
    this.rebuild(false);
    syncTicker();
  }

  async onClose(): Promise<void> { if(this.modelRefreshTimer)window.clearTimeout(this.modelRefreshTimer);if(this.initialFitTimer)window.clearTimeout(this.initialFitTimer);if(this.searchTimer)window.clearTimeout(this.searchTimer);for(const timer of this.folderTapTimers.values())window.clearTimeout(timer);this.cancelHoverIntent();this.savePositions(); this.worker?.terminate(); this.pixi?.destroy(true);for(const texture of this.nodeTextures.values())texture.destroy(true);this.nodeTextures.clear(); }

  rebuild(rebuildModel = true): void {
    this.cancelHoverIntent();this.focusAnimation++;this.focusProgress=0;this.focusTarget=0;this.focusPinned=false;this.hovered=undefined;this.hideTooltip();this.scene.filters=[];
    this.initialFitPending = true;
    this.physicsTicks = 0;
    this.physicsTargets.clear();
    if (rebuildModel) this.model = buildGraphModel(this.app, this.plugin.settings, this.plugin.data.positions);
    this.applyScopeFlags();
    this.buildScene();
    this.startActiveWorker(true);
    requestAnimationFrame(()=>this.fit());if(this.initialFitTimer)window.clearTimeout(this.initialFitTimer);this.initialFitTimer=window.setTimeout(()=>{if(this.initialFitPending)this.fit()},900);
    this.renderGraph();
  }

  private startActiveWorker(force=false):void {
    const active=this.model.nodes.filter(node=>node.visible),ids=activeNodeIds(this.model.nodes);if(!force&&this.worker&&sameNodeIds(ids,this.workerNodeIds))return;this.workerNodeIds=ids;
    this.worker?.terminate();this.physicsTargets.clear();
    this.worker = createPhysicsWorker();
    this.worker.onmessage = (event) => {
      if (event.data.type !== "tick"&&event.data.type!=="settled") return;
      for(const n of event.data.nodes as {id:string;x:number;y:number}[])this.physicsTargets.set(n.id,{x:n.x,y:n.y});this.motionUntil=performance.now()+180;if(this.activeLenses.size)this.lensGeometryDirty=true;
      if(event.data.type==="tick")this.physicsTicks++;
      if (event.data.type==="settled"&&this.initialFitPending) { this.initialFitPending = false;if(this.initialFitTimer)window.clearTimeout(this.initialFitTimer);this.fit(); }
      this.queueRender();
    };
    const edges=this.model.edges.filter(edge=>ids.has(edge.source)&&ids.has(edge.target));
    this.worker.postMessage({ type: "init", nodes: active.map(({id,x,y,visible,folder,degree,radius,path}) => ({id,x,y,visible,folder,degree,radius,group:this.search?"__search":this.physicsFolderGroup(path,folder)})), edges, opts: this.plugin.settings.forces, nodeScale:this.plugin.settings.display.nodeSize });
    if(this.searchRoles.size)this.worker.postMessage({type:"searchRoles",roles:[...this.searchRoles]});
  }

  updateForces(thorough=false): void { this.worker?.postMessage({ type: "forces", opts: this.plugin.settings.forces, thorough }); }

  private buildScene(): void {
    this.links.clear();
    this.focusLinks.clear();
    this.territoryLayer.removeChildren().forEach(child=>child.destroy({children:true}));this.lensShapes.clear();this.lastTerritoryUpdate=0;this.lensGeometryDirty=true;
    for(const layer of [this.focusGlowLayer,this.focusNodeLayer,this.focusLabelLayer])layer.removeChildren().forEach(child=>child.destroy());
    this.glowLayer.removeChildren().forEach((child) => child.destroy());
    this.nodeLayer.removeChildren().forEach((child) => child.destroy());
    this.labelLayer.removeChildren().forEach((child) => child.destroy());
    this.views.clear(); this.adjacency.clear();
    this.minRadius=Math.min(...this.model.nodes.map(n=>n.radius));this.maxRadius=Math.max(...this.model.nodes.map(n=>n.radius));
    for (const edge of this.model.edges) {
      if (!this.adjacency.has(edge.source)) this.adjacency.set(edge.source, new Set());
      if (!this.adjacency.has(edge.target)) this.adjacency.set(edge.target, new Set());
      this.adjacency.get(edge.source)?.add(edge.target); this.adjacency.get(edge.target)?.add(edge.source);
    }
    for (const node of this.model.nodes) { this.visibility.set(node.id,node.visible?1:0); this.createNodeView(node); }
  }

  private createNodeView(node: GraphNode): void {
    const glow=new Sprite(this.glowTexture);glow.anchor.set(.5);glow.eventMode="none";this.glowLayer.addChild(glow);
    const surface=new Sprite(this.getNodeTexture(node.color));surface.anchor.set(.5);surface.eventMode="none";this.nodeLayer.addChild(surface);
    const body = new Graphics(); body.eventMode = "static"; body.cursor = "pointer";
    body.on("pointerover", () => this.setHover(node));
    body.on("pointerout", () => {this.cancelHoverIntent(node);this.clearHover()});
    body.on("pointerdown", (e) => { if (e.button!==0) return; e.stopPropagation();if(e.ctrlKey)return; this.dragged=node; this.worker?.postMessage({type:"drag",id:node.id,x:node.x,y:node.y}); });
    body.on("pointerup", () => this.releaseNode()); body.on("pointerupoutside", () => this.releaseNode());
    body.on("pointertap", (event) => {event.stopPropagation();if(event.ctrlKey){this.openNodeInTab(node);return}if(event.detail>=2){this.openNode(node);return}this.pinFocus(node)});
    body.on("rightclick", (e) => this.contextMenu(node, e.global.x, e.global.y));
    this.nodeLayer.addChild(body);
    let icon: Text | undefined;
    if (node.icon) { icon = new Text({ text: node.icon, style: new TextStyle({ fontSize: 12,dropShadow:{color:0x000000,alpha:.72,blur:3,distance:1} }), resolution:Math.min(4,Math.max(2,window.devicePixelRatio*2)) }); icon.anchor.set(.5); icon.eventMode = "none";icon.roundPixels=true; this.nodeLayer.addChild(icon); }
    let label: Text | undefined,labelBg:Graphics|undefined;
    let leader:Graphics|undefined;
    if (node.alwaysLabel || node.degree > 2) {({label,labelBg}=this.makeLabel(node));leader=new Graphics();leader.eventMode="none";this.labelLayer.addChildAt(leader,0)}
    this.views.set(node.id, { node, body, surface, glow, icon, iconRes:icon?.resolution, label, labelBg,leader });
  }

  private makeLabel(node:GraphNode):{label:Text;labelBg:Graphics}{const labelBg=new Graphics();labelBg.eventMode="none";this.labelLayer.addChild(labelBg);const label=new Text({text:node.label,style:new TextStyle({fontSize:14,fontWeight:"600",fill:0xffffff,dropShadow:{color:0x000000,alpha:.6,blur:2,distance:1}})});label.anchor.set(.5);label.eventMode="none";this.labelLayer.addChild(label);this.drawLabelBackground(labelBg,label,node.color);return{label,labelBg}}
  private drawLabelBackground(background:Graphics,label:Text,color:string):void{const w=label.width+18,h=label.height+10,c=Number.parseInt(color.slice(1),16);background.clear().roundRect(-w/2,-h/2,w,h,12).fill({color:c,alpha:1}).stroke({color:0xffffff,alpha:.58,width:.7}).roundRect(-w/2+2,-h/2+2,w-4,h*.42,10).fill({color:0xffffff,alpha:.22})}
  private ensureLabel(node:GraphNode):void {const view=this.views.get(node.id);if(!view||view.label)return;const made=this.makeLabel(node);view.label=made.label;view.labelBg=made.labelBg;view.leader=new Graphics();view.leader.eventMode="none";this.labelLayer.addChildAt(view.leader,0)}

  private getNodeTexture(color:string):Texture {const cached=this.nodeTextures.get(color);if(cached)return cached;const canvas=document.createElement("canvas");canvas.width=canvas.height=256;const ctx=canvas.getContext("2d")!,rgb=/^#?([\da-f]{2})([\da-f]{2})([\da-f]{2})$/i.exec(color),r=rgb?Number.parseInt(rgb[1]!,16):138,g=rgb?Number.parseInt(rgb[2]!,16):148,b=rgb?Number.parseInt(rgb[3]!,16):166;ctx.save();ctx.beginPath();ctx.arc(128,128,119,0,Math.PI*2);ctx.clip();ctx.fillStyle=`rgb(${r},${g},${b})`;ctx.fillRect(0,0,256,256);const wash=ctx.createLinearGradient(0,8,0,248);wash.addColorStop(0,"rgba(255,255,255,.42)");wash.addColorStop(.42,"rgba(255,255,255,.08)");wash.addColorStop(.7,"rgba(0,0,0,.04)");wash.addColorStop(1,"rgba(0,0,0,.28)");ctx.fillStyle=wash;ctx.fillRect(0,0,256,256);const sheen=ctx.createRadialGradient(78,61,3,82,66,92);sheen.addColorStop(0,"rgba(255,255,255,.72)");sheen.addColorStop(.2,"rgba(255,255,255,.38)");sheen.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=sheen;ctx.fillRect(0,0,190,170);ctx.restore();ctx.beginPath();ctx.arc(128,128,119,0,Math.PI*2);ctx.strokeStyle="rgba(2,7,10,.58)";ctx.lineWidth=5;ctx.stroke();ctx.beginPath();ctx.arc(128,128,114.5,0,Math.PI*2);ctx.strokeStyle="rgba(255,255,255,.42)";ctx.lineWidth=3;ctx.stroke();const texture=Texture.from(canvas);this.nodeTextures.set(color,texture);return texture}

  private createGlowTexture():Texture {const canvas=document.createElement("canvas");canvas.width=canvas.height=128;const ctx=canvas.getContext("2d")!;const gradient=ctx.createRadialGradient(64,64,0,64,64,64);gradient.addColorStop(0,"rgba(255,255,255,.7)");gradient.addColorStop(.3,"rgba(255,255,255,.35)");gradient.addColorStop(1,"rgba(255,255,255,0)");ctx.fillStyle=gradient;ctx.fillRect(0,0,128,128);return Texture.from(canvas)}
  private queueRender(): void {
    this.renderQueued=true;
  }
  private animatePresentation(deltaMS:number):void {const now=performance.now();let moving=now<this.motionUntil,maxDelta=0;if(moving){const blend=1-Math.exp(-deltaMS/24);for(const node of this.model.nodes){const target=this.physicsTargets.get(node.id);if(!target)continue;const dx=target.x-node.x,dy=target.y-node.y;maxDelta=Math.max(maxDelta,Math.abs(dx),Math.abs(dy));node.x+=dx*blend;node.y+=dy*blend}moving=maxDelta>.02}if((this.renderQueued||moving)&&now-this.lastGeometryRender>=15){this.renderQueued=false;this.lastGeometryRender=now;this.renderGraph()}}

  private renderGraph(): void {
    this.world.position.set(this.offset.x, this.offset.y); this.world.scale.set(this.scale);
    this.focusWorld.position.set(this.offset.x,this.offset.y);this.focusWorld.scale.set(this.scale);
    this.focusBlur.strength=this.focusProgress*1.4;this.scene.filters=this.focusProgress>.01?[this.focusBlur]:[];if(this.pixi)this.scene.filterArea=this.pixi.screen;
    const visible = new Map(this.model.nodes.filter((n) => (this.visibility.get(n.id)??0)>.01).map((n) => [n.id, n]));
    const curvature=this.plugin.settings.forces.curvature,now=performance.now(),refreshBends=curvature>0&&now-this.lastBendUpdate>250,obstacleGrid=refreshBends?this.makeObstacleGrid():undefined;if(refreshBends)this.lastBendUpdate=now;
    if(this.lensGeometryDirty&&!this.zoomAnimating&&now-this.lastTerritoryUpdate>(now<this.motionUntil?280:80)){this.lastTerritoryUpdate=now;this.lensGeometryDirty=false;this.updateFolderLens()}
    this.links.clear();this.focusLinks.clear();
    for (const edge of this.model.edges) {
      const a = visible.get(edge.source), b = visible.get(edge.target); if (!a || !b) continue;const ar=this.searchRoles.get(a.id),br=this.searchRoles.get(b.id);if(ar==="hidden"||br==="hidden"||(ar==="context"&&br==="context"))continue;
      if(!this.plugin.settings.display.showSiblingLinks&&a.folder===b.folder)continue;
      const related = !this.hovered || this.hovered.id === a.id || this.hovered.id === b.id;
      this.links.moveTo(a.x, a.y);
      const key=`${edge.source}\0${edge.target}`;let bendState=this.edgeBends.get(key)??0;if(obstacleGrid){const raw=this.edgeBend(a,b,obstacleGrid),prior=this.edgeBends.get(key)??raw,target=Math.sign(raw)!==Math.sign(prior)&&Math.abs(raw)<.12?0:raw;bendState=prior+(target-prior)*.14;this.edgeBends.set(key,bendState)}const bend=bendState*curvature;
      if (Math.abs(bend)>.004) this.links.quadraticCurveTo((a.x+b.x)/2+(b.y-a.y)*bend,(a.y+b.y)/2-(b.x-a.x)*bend,b.x,b.y); else this.links.lineTo(b.x,b.y);
      const satelliteLink=ar==="context"||br==="context",lensEdgeAlpha=this.activeLenses.size&&!(this.lensMembers.has(a.id)&&this.lensMembers.has(b.id))?.175:1,edgeAlpha=(satelliteLink?.16:.32)*lensEdgeAlpha;
      this.links.stroke({ color: related ? 0x668899 : 0x334455, alpha: edgeAlpha, width: this.plugin.settings.display.linkThickness / this.scale });
      if(this.hovered&&related){this.focusLinks.moveTo(a.x,a.y);if(Math.abs(bend)>.004)this.focusLinks.quadraticCurveTo((a.x+b.x)/2+(b.y-a.y)*bend,(a.y+b.y)/2-(b.x-a.x)*bend,b.x,b.y);else this.focusLinks.lineTo(b.x,b.y);this.focusLinks.stroke({color:0x7da8b8,alpha:.42,width:this.plugin.settings.display.linkThickness/this.scale})}
    }
    const neighbors = this.hovered ? this.adjacency.get(this.hovered.id) : undefined;
    for (const view of this.views.values()) this.updateNodeView(view, !this.hovered || view.node.id === this.hovered.id || neighbors?.has(view.node.id) === true);
    this.layoutLabels();
    this.applyFocusFrame();
  }

  private updateNodeView(view: NodeView, related: boolean): void {
    const { node, body, surface, glow:glowSprite, icon, label, labelBg,leader } = view; const role=this.searchRoles.get(node.id),isContext=role==="context",focused=this.hovered?.id===node.id,color=isContext?0x8a94a6:Number.parseInt(node.color.slice(1), 16); const visibility=this.visibility.get(node.id)??0,focusAlpha=related?1:1-this.focusProgress*.85,lensAlpha=this.activeLenses.size&&!this.lensMembers.has(node.id)?.175:1,roleAlpha=isContext&&!focused?.5:1;
    const renderedRadius=isContext?Math.max(this.minRadius*.7,Math.min(node.radius*.55,this.minRadius*1.6)):node.radius,r=renderedRadius*this.plugin.settings.display.nodeSize; const glowScale=Math.max(.25,Math.min(1,7/r)),radiusT=(node.radius-this.minRadius)/Math.max(.001,this.maxRadius-this.minRadius),outerFactor=5-3*Math.max(0,Math.min(1,radiusT)),glowAmount=isContext||lensAlpha<1&&!focused?0:this.plugin.settings.display.glow*glowScale;
    const styleKey = `${r}`;
    if (view.styleKey !== styleKey) {
      body.clear().circle(0,0,r).fill({color:0xffffff,alpha:.001});
      body.hitArea={contains:(x:number,y:number)=>Math.hypot(x,y)<=r+5};
      if (icon) icon.style.fontSize=r*.9;
      view.styleKey = styleKey;
    }
    surface.position.set(node.x,node.y);surface.texture=this.getNodeTexture(isContext?"#8A94A6":node.color);surface.tint=0xffffff;surface.width=surface.height=r*2;surface.alpha=visibility*focusAlpha*lensAlpha*roleAlpha;surface.visible=visibility>.01;body.position.set(node.x,node.y); body.alpha=visibility*focusAlpha*lensAlpha*roleAlpha; body.visible=visibility>.01;
    const glowReach=r*(1+(outerFactor-1)*this.plugin.settings.display.glowSize);glowSprite.position.set(node.x,node.y);glowSprite.tint=color;glowSprite.width=glowSprite.height=glowReach*2;glowSprite.alpha=visibility*focusAlpha*glowAmount;glowSprite.visible=visibility>.01&&glowAmount>0;
    if (icon) { const screenRadius=r*this.scale,iconFade=node.hub?1:Math.max(0,Math.min(1,(screenRadius-7)/6)),smoothIconFade=iconFade*iconFade*(3-2*iconFade),visibleIcon=!isContext&&visibility>.01&&smoothIconFade>.01,wanted=this.scale>2.5?8:this.scale>1.2?4:2;if(visibleIcon&&view.iconRes!==wanted){icon.resolution=wanted;view.iconRes=wanted}icon.position.set(node.x,node.y);icon.alpha=visibility*focusAlpha*lensAlpha*smoothIconFade;icon.visible=visibleIcon; }
    if (label) { const screenRadius=r*this.scale,threshold=this.plugin.settings.display.textFade,band=Math.max(1.5,threshold*.075),raw=Math.max(0,Math.min(1,(screenRadius-threshold)/band+.5)),fade=raw*raw*(3-2*raw),persistent=node.alwaysLabel&&!isContext&&lensAlpha===1,focusedFade=focused||persistent?1:fade,labelScale=.05+.95*focusedFade,ordinaryLabel=lensAlpha===1&&!isContext&&(persistent||(this.scale>.35&&node.degree>2)),alpha=visibility*focusAlpha*(focused||persistent?1:lensAlpha*(.05+.95*fade)),y=node.y-r-13/this.scale;label.position.set(node.x,y);label.scale.set(labelScale/this.scale);label.alpha=alpha;label.visible=(focused||persistent||fade>.001)&&alpha>.01&&(focused||ordinaryLabel);if(labelBg){labelBg.position.set(node.x,y);labelBg.scale.set(labelScale/this.scale);labelBg.alpha=alpha;labelBg.visible=label.visible}if(leader&&!label.visible)leader.clear() }
  }

  private layoutLabels():void {
    for(const view of this.views.values())view.leader?.clear();
    const labels=[...this.views.values()].filter((v):v is NodeView&{label:Text;labelBg:Graphics}=>!!v.label&&!!v.labelBg&&v.label.visible).sort((a,b)=>Number(b.node.hub)-Number(a.node.hub)||b.node.degree-a.node.degree).map(v=>{const radius=v.node.radius*this.plugin.settings.display.nodeSize*this.scale,sx=this.offset.x+v.node.x*this.scale,sy=this.offset.y+v.node.y*this.scale,w=v.label.width+20,h=v.label.height+12;return{v,sx,sy,radius,w,h,x:sx,y:sy,homeX:sx,homeY:sy,side:-1 as 1|-1}});
    const pressure=(item:typeof labels[number],side:1|-1)=>{const y=item.sy+side*(item.radius+item.h/2+6);let score=y-item.h/2<8?8-(y-item.h/2):y+item.h/2>this.contentEl.clientHeight-8?y+item.h/2-(this.contentEl.clientHeight-8):0;for(const other of labels){if(other===item)continue;const ox=(item.w+other.w)/2+16-Math.abs(item.sx-other.sx),oy=item.h+other.radius+18-Math.abs(y-other.sy);if(ox>0&&oy>0)score+=ox*oy}return score};
    for(const item of labels){const above=pressure(item,-1),below=pressure(item,1),prior=this.labelOffsets.get(item.v.node.id),preferred=below+4<above?1:-1;item.side=prior&&pressure(item,prior.side)<=pressure(item,(prior.side*-1) as 1|-1)*1.15+8?prior.side:preferred;item.homeX=item.sx;item.homeY=item.sy+item.side*(item.radius+item.h/2+6);item.x=item.homeX+(prior?.x??0)*.72;item.y=item.homeY+(prior?.y??0)*.72}
    for(let pass=0;pass<7;pass++){for(const item of labels){item.x+=(item.homeX-item.x)*.16;item.y+=(item.homeY-item.y)*.16}for(let i=0;i<labels.length;i++)for(let j=i+1;j<labels.length;j++){const a=labels[i],b=labels[j];if(!a||!b)continue;const dx=b.x-a.x,dy=b.y-a.y,ox=(a.w+b.w)/2+4-Math.abs(dx),oy=(a.h+b.h)/2+3-Math.abs(dy);if(ox<=0||oy<=0)continue;const aWeight=a.v.node.hub?.32:.5,bWeight=b.v.node.hub?.32:.5;if(ox<oy){const push=Math.sign(dx||((j&1)?1:-1))*ox;a.x-=push*aWeight;b.x+=push*bWeight}else{const push=Math.sign(dy||1)*oy;a.y-=push*aWeight;b.y+=push*bWeight}}}
    for(const item of labels){const dx=Math.max(-120,Math.min(120,item.x-item.homeX)),dy=Math.max(-90,Math.min(90,item.y-item.homeY));this.labelOffsets.set(item.v.node.id,{x:dx,y:dy,side:item.side});const x=(item.homeX+dx-this.offset.x)/this.scale,y=(item.homeY+dy-this.offset.y)/this.scale;item.v.label.position.set(x,y);item.v.labelBg.position.set(x,y);if(item.v.leader&&item.v.label.alpha>.08){const nodeX=item.v.node.x,nodeY=item.v.node.y,vx=x-nodeX,vy=y-nodeY,distance=Math.max(.001,Math.hypot(vx,vy)),nx=vx/distance,ny=vy/distance,nodeRadius=item.v.node.radius*this.plugin.settings.display.nodeSize,startX=nodeX+nx*nodeRadius,startY=nodeY+ny*nodeRadius,halfW=item.w*.5/this.scale,halfH=item.h*.5/this.scale,edgeDistance=Math.min(halfW/Math.max(.001,Math.abs(nx)),halfH/Math.max(.001,Math.abs(ny))),endX=x-nx*edgeDistance,endY=y-ny*edgeDistance,pressure=Math.min(1,Math.hypot(dx,dy)/36),curve=(dx*ny-dy*nx)*.08/this.scale,mx=(startX+endX)/2-ny*curve,my=(startY+endY)/2+nx*curve;item.v.leader.moveTo(startX,startY).quadraticCurveTo(mx,my,endX,endY).stroke({color:Number.parseInt(item.v.node.color.slice(1),16),alpha:(.32+pressure*.34)*item.v.label.alpha,width:.9/this.scale})}}
  }

  private applyScopeFlags():void {for(const node of this.model.nodes)node.visible=nodeAllowed(node.path,this.plugin.settings.groups,this.plugin.settings.other.visible)&&isPathInFolderScope(node.path,this.folderScope)}
  private updateFolderLens():void {
    const eligible=this.model.nodes.filter(node=>node.visible),members=unionLensMembership(eligible.map(node=>node.path),this.activeLenses);this.lensMembers=new Set(members);
    const groups=new Map<string,GraphNode[]>();for(const node of eligible){if(!members.has(node.path))continue;const group=groups.get(node.color)??[];group.push(node);groups.set(node.color,group)}
    const wanted=new Set(groups.keys()),details:{color:string;nodes:number;components:number;cellSize:number;columns:number;rows:number}[]=[];for(const [color,nodes] of groups){let shape=this.lensShapes.get(color);if(!shape){shape=new Graphics();shape.eventMode="none";this.territoryLayer.addChild(shape);this.lensShapes.set(color,shape)}shape.clear();const padding=28*this.plugin.settings.display.lensRadius,result=buildLensContours(nodes.map(node=>({x:node.x,y:node.y,radius:node.radius*this.plugin.settings.display.nodeSize})),{padding,maxGridCells:180,smoothingPasses:2}),fillAlpha=Math.max(.04,Math.min(.6,this.plugin.settings.display.lensOpacity)),numericColor=Number.parseInt(color.slice(1),16);for(const contour of result.contours){const component=nodes.filter(node=>this.pointInLensContour(node.x,node.y,contour));if(component.length===1)this.drawSingleNodeLens(shape,component[0]!,padding,numericColor,fillAlpha);else this.drawSmoothLensContour(shape,component.length<=5?this.lowCardinalityLensContour(component,padding):contour,numericColor,fillAlpha)}details.push({color,nodes:nodes.length,components:result.contours.length,cellSize:Number(result.cellSize.toFixed(2)),columns:result.columns,rows:result.rows})}
    for(const [color,shape] of this.lensShapes)if(!wanted.has(color)){shape.destroy();this.lensShapes.delete(color)}
    const signature=JSON.stringify({lenses:[...this.activeLenses].sort(),eligible:eligible.length,members:members.size,details,scale:Number(this.scale.toFixed(3)),opacity:this.plugin.settings.display.lensOpacity,radius:this.plugin.settings.display.lensRadius});if(signature!==this.lensDiagnosticSignature){this.lensDiagnosticSignature=signature;const first=this.lensShapes.values().next().value;this.plugin.logDiagnostic("lens-contour-state",{activeLenses:[...this.activeLenses],eligibleNodes:eligible.length,memberNodes:members.size,memberSample:[...members].slice(0,5),groups:details,shapeCount:this.lensShapes.size,territoryAttached:this.territoryLayer.parent===this.world,worldAttached:this.world.parent===this.scene,sceneAttached:this.scene.parent===this.pixi?.stage,layerVisible:this.territoryLayer.visible,layerRenderable:this.territoryLayer.renderable,firstShape:first?{visible:first.visible,renderable:first.renderable,parentAttached:first.parent===this.territoryLayer}:null})}
  }
  private pointInLensContour(x:number,y:number,contour:{x:number;y:number}[]):boolean {let inside=false;for(let i=0,j=contour.length-1;i<contour.length;j=i++){const a=contour[i]!,b=contour[j]!;if((a.y>y)!==(b.y>y)&&x<(b.x-a.x)*(y-a.y)/(b.y-a.y)+a.x)inside=!inside}return inside}
  private drawSingleNodeLens(shape:Graphics,node:GraphNode,padding:number,color:number,fillAlpha:number):void {const radius=node.radius*this.plugin.settings.display.nodeSize+padding;shape.circle(node.x,node.y,radius).fill({color,alpha:fillAlpha}).stroke({color,alpha:Math.min(.82,fillAlpha*2.8+.18),width:Math.max(.8,1.6/this.scale)})}
  private lowCardinalityLensContour(nodes:GraphNode[],padding:number):{x:number;y:number}[]{const samples:{x:number;y:number}[]=[];for(const node of nodes){const radius=node.radius*this.plugin.settings.display.nodeSize+padding;for(let index=0;index<24;index++){const angle=index/24*Math.PI*2;samples.push({x:node.x+Math.cos(angle)*radius,y:node.y+Math.sin(angle)*radius})}}samples.sort((a,b)=>a.x-b.x||a.y-b.y);const cross=(o:{x:number;y:number},a:{x:number;y:number},b:{x:number;y:number})=>(a.x-o.x)*(b.y-o.y)-(a.y-o.y)*(b.x-o.x),lower:{x:number;y:number}[]=[],upper:{x:number;y:number}[]=[];for(const point of samples){while(lower.length>=2&&cross(lower[lower.length-2]!,lower[lower.length-1]!,point)<=0)lower.pop();lower.push(point)}for(let index=samples.length-1;index>=0;index--){const point=samples[index]!;while(upper.length>=2&&cross(upper[upper.length-2]!,upper[upper.length-1]!,point)<=0)upper.pop();upper.push(point)}lower.pop();upper.pop();return lower.concat(upper)}
  private drawSmoothLensContour(shape:Graphics,contour:{x:number;y:number}[],color:number,fillAlpha:number):void {if(contour.length<3)return;const step=Math.max(1,Math.ceil(contour.length/180));let points=contour.filter((_,index)=>index%step===0);if(points.length<3)return;const passes=points.length<24?8:points.length<60?6:4;for(let pass=0;pass<passes;pass++){const source=points;points=source.map((point,index)=>{const previous=source[(index-1+source.length)%source.length]!,next=source[(index+1)%source.length]!;return{x:point.x*.34+(previous.x+next.x)*.33,y:point.y*.34+(previous.y+next.y)*.33}})}shape.moveTo(points[0]!.x,points[0]!.y);for(let index=0;index<points.length;index++){const p0=points[(index-1+points.length)%points.length]!,p1=points[index]!,p2=points[(index+1)%points.length]!,p3=points[(index+2)%points.length]!,tension=1,cp1x=p1.x+(p2.x-p0.x)*tension/6,cp1y=p1.y+(p2.y-p0.y)*tension/6,cp2x=p2.x-(p3.x-p1.x)*tension/6,cp2y=p2.y-(p3.y-p1.y)*tension/6;shape.bezierCurveTo(cp1x,cp1y,cp2x,cp2y,p2.x,p2.y)}shape.closePath().fill({color,alpha:fillAlpha}).stroke({color,alpha:Math.min(.82,fillAlpha*2.8+.18),width:Math.max(.8,1.6/this.scale)})}
  private handleFolderTap(path:string):void {const existing=this.folderTapTimers.get(path);if(existing){window.clearTimeout(existing);this.folderTapTimers.delete(path);this.openFolderIndex(path);return}const timer=window.setTimeout(()=>{this.folderTapTimers.delete(path);if(path!==this.folderScope)this.enterFolderScope(path)},230);this.folderTapTimers.set(path,timer)}
  private openFolderIndex(path:string):void {const indexPath=path?`${path}/index.md`:"index.md",file=this.app.vault.getAbstractFileByPath(indexPath);if(file instanceof TFile)void this.app.workspace.getLeaf().openFile(file);else new Notice(`No index.md found in ${folderDisplayName(path)}.`)}
  private async revealFolder(path:string):Promise<void>{const folder=this.app.vault.getAbstractFileByPath(path);if(!(folder instanceof TFolder)){new Notice(`Folder ${folderDisplayName(path)} is unavailable.`);return}let leaf=this.app.workspace.getLeavesOfType("file-explorer")[0];if(!leaf){leaf=this.app.workspace.getLeftLeaf(false)??undefined;if(leaf)await leaf.setViewState({type:"file-explorer",active:true})}if(!leaf){new Notice("Open Obsidian's File Explorer first.");return}this.app.workspace.revealLeaf(leaf);const explorer=leaf.view as unknown as {revealInFolder?:(file:TFolder)=>void|Promise<void>};if(explorer.revealInFolder)await explorer.revealInFolder(folder);else new Notice("This Obsidian version does not expose folder reveal to plugins.")}
  private enterFolderScope(scope:string):void {this.scopeHistory.push({scope:this.folderScope,scale:this.scale,offset:{...this.offset}});this.setFolderScope(scope);window.setTimeout(()=>this.fit(),420)}
  private leaveFolderScope(scope:string):void {const index=this.scopeHistory.map(state=>state.scope).lastIndexOf(scope),state=index>=0?this.scopeHistory[index]:undefined;if(index>=0)this.scopeHistory.splice(index);this.setFolderScope(scope);window.setTimeout(()=>{if(state){this.zoomTarget={scale:state.scale,x:state.offset.x,y:state.offset.y};this.animateZoom()}else this.fit()},320)}
  private setFolderScope(scope:string):void {this.cancelHoverIntent();this.focusPinned=false;this.clearHoverImmediate();this.folderScope=scope;for(const lens of [...this.activeLenses])if(!isPathInFolder(lens,scope)&&!isPathInFolder(scope,lens))this.activeLenses.delete(lens);const changed:string[]=[];for(const node of this.model.nodes){const visible=nodeAllowed(node.path,this.plugin.settings.groups,this.plugin.settings.other.visible)&&isPathInFolderScope(node.path,scope);if(node.visible!==visible)changed.push(node.id);node.visible=visible}this.lensGeometryDirty=true;this.startActiveWorker();this.animateNodeVisibility(changed);this.updateBreadcrumb();this.updateGraphCount();this.refreshLensToolbar();void this.plugin.persistData()}
  private physicsFolderGroup(_path:string,fallback:string):string{return fallback}
  private animateNodeVisibility(ids:string[]):void {const token=++this.visibilityAnimation,targets=new Map(ids.map(id=>{const node=this.model.nodes.find(candidate=>candidate.id===id);return[id,node?.visible?1:0] as const})),from=new Map(ids.map(id=>[id,this.visibility.get(id)??(targets.get(id)?0:1)])),start=performance.now();const tick=(now:number)=>{if(token!==this.visibilityAnimation)return;const progress=Math.min(1,(now-start)/300),ease=progress*progress*(3-2*progress);for(const [id,value] of from)this.visibility.set(id,value+((targets.get(id)??0)-value)*ease);this.renderGraph();if(progress<1)requestAnimationFrame(tick);else for(const [id,target] of targets)this.visibility.set(id,target)};requestAnimationFrame(tick)}
  private updateGraphCount():void {const count=this.contentEl.querySelector<HTMLElement>(".beautiful-graph-count"),visible=this.model.nodes.filter(node=>node.visible).length,total=this.model.nodes.length;if(count)count.textContent=visible<total?`${visible} / ${total} Nodes`:`${total} Nodes`}
  private updateBreadcrumb():void {this.contentEl.querySelector(".beautiful-graph-breadcrumb")?.remove();if(!this.folderScope)return;const bar=this.contentEl.createDiv({cls:"beautiful-graph-breadcrumb"}),parts=this.folderScope.split("/");const home=bar.createEl("button",{text:"Vault"});home.onclick=()=>this.leaveFolderScope("");let path="";for(let index=0;index<parts.length;index++){bar.createSpan({text:"›"});path=path?`${path}/${parts[index]}`:parts[index]!;if(index===parts.length-1)bar.createSpan({cls:"is-current",text:folderDisplayName(path)});else{const target=path,button=bar.createEl("button",{text:folderDisplayName(path)});button.onclick=()=>this.leaveFolderScope(target)}}}

  private setHover(node: GraphNode): void {if(this.focusPinned||this.hoverCandidate===node.id||(this.hovered?.id===node.id&&this.focusTarget===1))return;this.cancelHoverIntent();this.hoverCandidate=node.id;this.hoverTimer=window.setTimeout(()=>{if(this.hoverCandidate!==node.id||this.focusPinned)return;this.hoverTimer=undefined;this.hoverCandidate=undefined;this.ensureLabel(node);this.hovered=node;this.setFocusLayers(node);this.showTooltip(node);this.renderGraph();this.animateFocus(1)},200)}
  private cancelHoverIntent(node?:GraphNode):void {if(node&&this.hoverCandidate!==node.id)return;if(this.hoverTimer)window.clearTimeout(this.hoverTimer);this.hoverTimer=undefined;this.hoverCandidate=undefined}
  private pinFocus(node:GraphNode):void {this.cancelHoverIntent();this.focusPinned=true;this.ensureLabel(node);this.hovered=node;this.setFocusLayers(node);this.showTooltip(node);this.renderGraph();this.animateFocus(1);if(this.plugin.settings.display.recenterOnFocus)this.focusNode(node)}
  private unpinFocus():void {if(!this.focusPinned)return;this.focusPinned=false;this.clearHover()}
  private clearHover(): void { if (this.focusPinned||!this.hovered||this.focusTarget===0) return;this.hideTooltip();this.animateFocus(0,()=>{this.hovered=undefined;this.setFocusLayers();this.renderGraph()}); }
  private clearHoverImmediate():void {this.cancelHoverIntent();if(this.focusPinned||!this.hovered)return;this.focusAnimation++;this.focusTarget=0;this.focusProgress=0;this.hovered=undefined;this.hideTooltip();this.setFocusLayers();this.scene.filters=[];this.renderGraph()}
  private animateFocus(target:number,done?:()=>void):void {this.focusTarget=target;const token=++this.focusAnimation,start=this.focusProgress,begin=performance.now();const tick=(now:number)=>{if(token!==this.focusAnimation)return;const p=Math.min(1,(now-begin)/110),ease=p*p*(3-2*p);this.focusProgress=start+(target-start)*ease;this.renderFocusFrame();if(p<1)requestAnimationFrame(tick);else done?.()};requestAnimationFrame(tick)}
  private renderFocusFrame():void {const neighbors=this.hovered?this.adjacency.get(this.hovered.id):undefined;for(const view of this.views.values())this.updateNodeView(view,!this.hovered||view.node.id===this.hovered.id||neighbors?.has(view.node.id)===true);this.layoutLabels();this.applyFocusFrame()}
  private applyFocusFrame():void {this.focusBlur.strength=this.focusProgress*1.4;this.scene.filters=this.focusProgress>.01?[this.focusBlur]:[];if(this.pixi)this.scene.filterArea=this.pixi.screen;this.links.alpha=this.hovered?1-this.focusProgress*.88:1;this.focusLinks.alpha=this.hovered?this.focusProgress:0}
  private setFocusLayers(node?:GraphNode):void {const neighbors=node?this.adjacency.get(node.id):undefined;for(const view of this.views.values()){const focused=!!node&&(view.node.id===node.id||neighbors?.has(view.node.id)===true);(focused?this.focusGlowLayer:this.glowLayer).addChild(view.glow);(focused?this.focusNodeLayer:this.nodeLayer).addChild(view.surface);(focused?this.focusNodeLayer:this.nodeLayer).addChild(view.body);if(view.icon)(focused?this.focusNodeLayer:this.nodeLayer).addChild(view.icon);if(view.labelBg)(focused?this.focusLabelLayer:this.labelLayer).addChild(view.labelBg);if(view.label)(focused?this.focusLabelLayer:this.labelLayer).addChild(view.label)}}

  private createToolbar(): void { const bar=this.contentEl.createDiv({cls:"beautiful-graph-toolbar"});bar.createSpan({cls:"beautiful-graph-count",text:`${this.model.nodes.length} Nodes`});const input=bar.createEl("input",{type:"search",placeholder:"Filter graph…"});this.searchInput=input;input.addEventListener("input",()=>{if(this.searchTimer)window.clearTimeout(this.searchTimer);this.searchTimer=window.setTimeout(()=>void this.applySearch(input.value),250)});input.addEventListener("keydown",e=>{if(e.key==="Escape"){input.value="";void this.applySearch("")}});bar.createEl("button",{text:"Fit"}).onclick=()=>{this.fit();this.focusSearchSoon()};this.focusSearchSoon(); }
  private focusSearchSoon():void{window.setTimeout(()=>{const active=document.activeElement;if(!(active instanceof HTMLInputElement)||active===this.searchInput)this.searchInput?.focus()},0)}
  public toggleFolderLens(path:string):void{if(!this.plugin.settings.groups.some(g=>g.root===path))return;const selecting=!this.activeLenses.has(path);if(selecting)this.activeLenses.add(path);else this.activeLenses.delete(path);this.lastTerritoryUpdate=0;this.lensGeometryDirty=true;this.lensDiagnosticSignature="";this.plugin.logDiagnostic("lens-toggle",{path,selecting,activeLenses:[...this.activeLenses],modelNodes:this.model.nodes.length});this.createPanels();this.renderGraph()}
  public enterLensScope(path:string):void{this.enterFolderScope(path)}
  public hasFolderLens(path:string):boolean{return this.activeLenses.has(path)}
  public useOnlyFolderLens(path:string):void{this.activeLenses.clear();this.activeLenses.add(path);this.lensGeometryDirty=true;this.syncFileExplorerLensRows();this.createPanels();this.renderGraph();this.retainInteractionFocus()}
  public toggleFolderGroup(path:string):void{const found=this.plugin.settings.groups.find(g=>g.root===path);this.pushHistory();if(found)this.plugin.settings.groups=this.plugin.settings.groups.filter(g=>g.id!==found.id);else this.plugin.settings.groups.push(this.makeManualGroup(path));this.applyGroupChanges();this.retainInteractionFocus()}
  public toggleGroupVisibility(path:string):void{const group=this.plugin.settings.groups.find(g=>g.root===path);if(!group)return;this.pushHistory();group.visible=!group.visible;this.applyGroupChanges();this.retainInteractionFocus()}
  public revealFolderGroup(path:string):void{const panel=this.contentEl.querySelector<HTMLElement>(".beautiful-panel-groups"),row=Array.from(this.contentEl.querySelectorAll<HTMLElement>(".beautiful-group-row")).find(el=>el.title===path);if(panel){panel.style.zIndex=String(++this.panelZ);row?.scrollIntoView({block:"center",behavior:"smooth"});row?.animate([{background:"#44d7b644"},{background:"transparent"}],{duration:900})}this.retainInteractionFocus()}
  public editFolderGroup(path:string):void{this.revealFolderGroup(path);const row=Array.from(this.contentEl.querySelectorAll<HTMLElement>(".beautiful-group-row")).find(el=>el.title===path);row?.querySelector<HTMLButtonElement>(".beautiful-group-swatch")?.click()}
  public retainInteractionFocus():void{this.app.workspace.setActiveLeaf(this.leaf,{focus:false});window.setTimeout(()=>this.searchInput?.focus({preventScroll:true}),0)}
  public pinExternalSelection(path:string):boolean{const node=this.model.nodes.find(candidate=>candidate.path===path);if(!node||!node.visible)return false;this.cancelHoverIntent();this.focusPinned=true;this.ensureLabel(node);this.hovered=node;this.setFocusLayers(node);this.showTooltip(node);this.renderGraph();this.animateFocus(1);return true}
  private refreshLensToolbar():void{this.createPanels()}
  private syncFileExplorerLensRows():void{const rows=Array.from(document.querySelectorAll(".nav-folder-title")) as HTMLElement[];for(const row of rows){row.removeClass("beautiful-lens-active");row.style.removeProperty("--beautiful-lens-color")}for(const row of rows){const owner=(row.closest("[data-path]") as HTMLElement|null)??row,path=row.dataset.path??owner.dataset.path??owner.getAttribute("data-path");if(!path||!this.activeLenses.has(path))continue;row.addClass("beautiful-lens-active");const member=this.model.nodes.find(node=>isPathInFolder(node.path,path));row.style.setProperty("--beautiful-lens-color",member?.color??"#44D7B6")}}
  private async applySearch(raw:string):Promise<void>{const generation=++this.searchGeneration,query=raw.trim().toLowerCase();this.search=query;if(!query){this.searchRoles.clear();this.applyScopeFlags();this.syncWorkerVisibility();this.renderGraph();return}const eligible=this.model.nodes.filter(node=>nodeAllowed(node.path,this.plugin.settings.groups,this.plugin.settings.otherVisible)&&isPathInFolderScope(node.path,this.folderScope));await Promise.all(eligible.map(async node=>{if(this.searchIndex.has(node.id))return;const file=this.app.vault.getAbstractFileByPath(node.path);const content=file instanceof TFile?await this.app.vault.cachedRead(file):"";const cache=file instanceof TFile?this.app.metadataCache.getFileCache(file):null;this.searchIndex.set(node.id,`${node.label}\n${node.path}\n${content}\n${JSON.stringify(cache?.frontmatter??{})}\n${(cache?.tags??[]).map(tag=>tag.tag).join(" ")}`.toLowerCase())}));if(generation!==this.searchGeneration)return;const terms=query.split(/\s+/).filter(Boolean),matches=new Set(eligible.filter(node=>terms.every(term=>(this.searchIndex.get(node.id)??"").includes(term))).map(node=>node.id)),context=new Set<string>();for(const id of matches)for(const neighbor of this.adjacency.get(id)??[])if(!matches.has(neighbor))context.add(neighbor);this.searchRoles.clear();for(const node of eligible)this.searchRoles.set(node.id,matches.has(node.id)?"match":context.has(node.id)?"context":"hidden");for(const node of this.model.nodes){const role=this.searchRoles.get(node.id);node.visible=role!=="hidden"&&(role!=="context"||this.plugin.settings.display.showLinkedInSearch)&&nodeAllowed(node.path,this.plugin.settings.groups,this.plugin.settings.otherVisible)&&isPathInFolderScope(node.path,this.folderScope)}this.syncWorkerVisibility();this.renderGraph();this.updateGraphCount()}
  private syncWorkerVisibility():void{this.lensGeometryDirty=true;this.startActiveWorker();const changed=this.model.nodes.map(node=>node.id);this.animateNodeVisibility(changed)}
  private createPanels(): void {
    this.contentEl.querySelectorAll(".beautiful-graph-panel").forEach(el=>el.remove());
    this.createGroupsPanel();
    this.createForcesPanel();
    this.createDisplayPanel();
  }
  private createGroupsPanel():void{this.createPanel("groups","Groups",body=>{
    body.addClass("beautiful-groups-body");const all=body.createEl("label",{cls:"beautiful-groups-all"}),allBox=all.createEl("input",{type:"checkbox"}),visible=this.plugin.settings.groups.filter(g=>g.visible).length+(this.plugin.settings.other.visible?1:0),total=this.plugin.settings.groups.length+1;allBox.checked=visible===total;allBox.indeterminate=visible>0&&visible<total;all.createSpan({text:"Show on graph"});all.createSpan({cls:"beautiful-filter-count",text:String(this.model.nodes.length)});allBox.onchange=()=>{this.pushHistory();for(const g of this.plugin.settings.groups)g.visible=allBox.checked;this.plugin.settings.other.visible=allBox.checked;this.plugin.settings.otherVisible=allBox.checked;this.applyGroupChanges()};
    const lenses=body.createDiv({cls:"beautiful-groups-lenses"});this.slider(lenses,"Lens opacity",this.plugin.settings.display.lensOpacity,0,.52,.01,v=>{this.plugin.settings.display.lensOpacity=v;this.lensGeometryDirty=true;void this.plugin.persistData();this.renderGraph()});this.slider(lenses,"Lens radius",this.plugin.settings.display.lensRadius,.25,3.17,.01,v=>{this.plugin.settings.display.lensRadius=v;this.lensGeometryDirty=true;void this.plugin.persistData();this.renderGraph()});
    const tree=body.createDiv({cls:"beautiful-groups-tree"}),groups=this.plugin.settings.groups.slice().sort((a,b)=>a.order-b.order||a.root.localeCompare(b.root));for(const group of groups)this.renderGroupRow(tree,group);this.renderOtherGroupRow(tree);this.renderRootIndexRow(tree);requestAnimationFrame(()=>{const widths=Array.from(tree.querySelectorAll<HTMLElement>(".beautiful-group-name")).map(el=>el.scrollWidth);tree.style.setProperty("--group-pill-width",`${Math.min(126,Math.max(58,...widths)+4)}px`)});
    const footer=body.createDiv({cls:"beautiful-groups-footer"}),paletteRow=footer.createDiv({cls:"beautiful-palette-row"}),paletteNames=Object.keys(GROUP_PALETTES),theme=paletteRow.createEl("button",{cls:"beautiful-palette-theme",text:this.plugin.settings.groupPalette}),applyPalette=(index:number)=>{this.pushHistory();const name=paletteNames[(index+paletteNames.length)%paletteNames.length]!,colors=GROUP_PALETTES[name]!;this.plugin.settings.groupPalette=name;this.plugin.settings.groups.slice().sort((a,b)=>a.order-b.order).forEach((g,i)=>g.color=colors[i%colors.length]!);theme.textContent=name;for(const group of this.plugin.settings.groups){const row=Array.from(tree.querySelectorAll<HTMLElement>(".beautiful-group-row")).find(candidate=>candidate.title===group.root);row?.style.setProperty("--group-color",group.color);const swatch=row?.querySelector<HTMLElement>(".beautiful-group-swatch");if(swatch)swatch.style.backgroundColor=group.color}this.applyPresentationChanges()};theme.onclick=()=>applyPalette(paletteNames.indexOf(this.plugin.settings.groupPalette)+1);paletteRow.createEl("button",{text:"←",attr:{"aria-label":"Previous Group palette"}}).onclick=()=>applyPalette(paletteNames.indexOf(this.plugin.settings.groupPalette)-1);paletteRow.createEl("button",{text:"→",attr:{"aria-label":"Next Group palette"}}).onclick=()=>applyPalette(paletteNames.indexOf(this.plugin.settings.groupPalette)+1);const actions=footer.createDiv({cls:"beautiful-group-actions"});actions.createEl("button",{text:"Analyze & Auto Group"}).onclick=()=>this.analyzeAndAutoGroup();const deleteAll=actions.createEl("button",{text:"Delete All Groups"});deleteAll.onclick=()=>{this.deleteAllGroups();const update=()=>{const seconds=Math.ceil(((this.presetOverwriteArmed.get("delete-all-groups")??0)-Date.now())/1000);if(seconds>0&&deleteAll.isConnected){deleteAll.addClass("is-armed");deleteAll.textContent=`Confirm (${seconds}s)`;window.setTimeout(update,250)}else if(deleteAll.isConnected){deleteAll.removeClass("is-armed");deleteAll.textContent="Delete All Groups"}};update()};this.addGroupsPresetControls(footer);
  })}
  private makeManualGroup(path:string){const colors=GROUP_PALETTES[this.plugin.settings.groupPalette]??GROUP_PALETTES["Beautiful Default"]!;return{id:`manual:${Date.now()}`,root:path,color:colors[this.plugin.settings.groups.length%colors.length]!,icon:defaultGroupIcon(path),visible:true,origin:"manual" as const,order:this.plugin.settings.groups.length}}
  private renderGroupRow(tree:HTMLElement,group:BeautifulGraphSettings["groups"][number]):void{const row=tree.createDiv({cls:"beautiful-group-row"});row.title=group.root;row.toggleClass("is-lens-active",this.activeLenses.has(group.root));row.style.setProperty("--group-color",group.color);const shown=row.createEl("input",{type:"checkbox"});shown.checked=group.visible;shown.onchange=()=>{this.pushHistory();group.visible=shown.checked;this.applyGroupChanges()};const swatch=row.createEl("button",{cls:"beautiful-group-swatch",attr:{"aria-label":`Change ${group.root} color`}});swatch.style.backgroundColor=group.color;const color=row.createEl("input",{type:"color",cls:"beautiful-group-color"});color.value=group.color;swatch.onclick=()=>color.click();color.oninput=()=>{group.color=color.value;row.style.setProperty("--group-color",group.color);swatch.style.backgroundColor=color.value;this.applyPresentationChanges()};const icon=row.createEl("input",{type:"text",cls:"beautiful-group-icon",value:group.icon||defaultGroupIcon(group.root)});this.bindIconEditor(icon,()=>group.icon,value=>group.icon=value,defaultGroupIcon(group.root));const name=row.createEl("button",{cls:"beautiful-group-name",text:displayDirectory(group.root.split("/").at(-1)??group.root,this.plugin.settings.replaceUnderscores,this.plugin.settings.capitalizeDirectories)});name.onclick=()=>this.toggleFolderLens(group.root);row.createSpan({cls:"beautiful-filter-count",text:String(this.model.nodes.filter(n=>effectiveGroup(n.path,this.plugin.settings.groups)?.id===group.id).length)});const remove=row.createEl("button",{cls:"beautiful-group-delete",text:"x",attr:{"aria-label":`Delete ${group.root} Group`}});remove.onclick=()=>{this.pushHistory();this.activeLenses.delete(group.root);this.plugin.settings.groups=this.plugin.settings.groups.filter(g=>g.id!==group.id);this.applyGroupChanges()}}
  private renderOtherGroupRow(tree:HTMLElement):void{const group=this.plugin.settings.other,row=tree.createDiv({cls:"beautiful-group-row beautiful-group-other"}),shown=row.createEl("input",{type:"checkbox"});shown.checked=group.visible;shown.onchange=()=>{this.pushHistory();group.visible=shown.checked;this.plugin.settings.otherVisible=shown.checked;this.applyGroupChanges()};const swatch=row.createEl("button",{cls:"beautiful-group-swatch"});swatch.style.backgroundColor=group.color;const color=row.createEl("input",{type:"color",cls:"beautiful-group-color"});color.value=group.color;swatch.onclick=()=>color.click();color.oninput=()=>{group.color=color.value;swatch.style.backgroundColor=color.value;this.applyPresentationChanges()};const icon=row.createEl("input",{type:"text",cls:"beautiful-group-icon",value:group.icon||"📂"});this.bindIconEditor(icon,()=>group.icon,value=>group.icon=value,"📂");row.createSpan({cls:"beautiful-group-name",text:"Other"});row.createSpan({cls:"beautiful-filter-count",text:String(this.model.nodes.filter(n=>!effectiveGroup(n.path,this.plugin.settings.groups)).length)})}
  private renderRootIndexRow(tree:HTMLElement):void{const setting=this.plugin.settings.rootIndex,row=tree.createDiv({cls:"beautiful-group-row beautiful-root-index"}),toggle=row.createEl("button",{cls:`beautiful-root-toggle${setting.enabled?" is-on":""}`,attr:{"aria-label":"Toggle Root Index styling"}});toggle.onclick=()=>{this.pushHistory();setting.enabled=!setting.enabled;toggle.toggleClass("is-on",setting.enabled);this.applyPresentationChanges()};const swatch=row.createEl("button",{cls:"beautiful-group-swatch"});swatch.style.backgroundColor=setting.color;const color=row.createEl("input",{type:"color",cls:"beautiful-group-color"});color.value=setting.color;swatch.onclick=()=>color.click();color.oninput=()=>{setting.color=color.value;swatch.style.backgroundColor=color.value;this.applyPresentationChanges()};const icon=row.createEl("input",{type:"text",cls:"beautiful-group-icon",value:setting.icon||"🌱"});this.bindIconEditor(icon,()=>setting.icon,value=>setting.icon=value,"🌱");row.createSpan({cls:"beautiful-group-name",text:"Root Index"});const linked=row.createEl("label",{cls:"beautiful-root-linked"}),linkedBox=linked.createEl("input",{type:"checkbox"});linkedBox.checked=setting.includeLinked;linked.createSpan({text:"Include linked"});linkedBox.onchange=()=>{this.pushHistory();setting.includeLinked=linkedBox.checked;this.applyPresentationChanges()}}
  private addGroupsPresetControls(body:HTMLElement):void{const row=body.createDiv({cls:"beautiful-preset-row"}),input=row.createEl("input",{type:"text",placeholder:"Name custom preset..."}),presets=this.plugin.settings.groupPresets;row.createEl("button",{text:"Load"}).onclick=()=>{const p=presets[input.value.trim()];if(!p)return;this.pushHistory();this.plugin.settings.groups=structuredClone(p.groups);this.plugin.settings.other=structuredClone(p.other);this.plugin.settings.rootIndex={...this.plugin.settings.rootIndex,...structuredClone(p.rootIndex??{})};this.plugin.settings.otherVisible=p.other.visible;this.plugin.settings.groupPalette=p.paletteId;this.plugin.settings.display.lensOpacity=p.lensOpacity;this.plugin.settings.display.lensRadius=p.lensRadius;this.applyGroupChanges()};row.createEl("button",{text:"Save"}).onclick=()=>{const name=input.value.trim();if(!name){new Notice("Enter a preset name first.");return}presets[name]={groups:structuredClone(this.plugin.settings.groups),other:structuredClone(this.plugin.settings.other),rootIndex:structuredClone(this.plugin.settings.rootIndex),paletteId:this.plugin.settings.groupPalette,lensOpacity:this.plugin.settings.display.lensOpacity,lensRadius:this.plugin.settings.display.lensRadius};void this.plugin.persistData();new Notice(`Groups preset “${name}” saved.`);this.focusSearchSoon()};row.createEl("button",{text:"Delete"}).onclick=()=>{const name=input.value.trim();if(!presets[name])return;delete presets[name];void this.plugin.persistData();input.value="";new Notice(`Groups preset “${name}” deleted.`)}}
  private bindIconEditor(input:HTMLInputElement,getValue:()=>string,setValue:(value:string)=>void,fallback:string):void{let composing=false;input.addEventListener("compositionstart",()=>composing=true);const update=()=>{setValue(input.value);this.applyPresentationChanges()};const commit=()=>{if(composing)return;const value=normalizeIcon(input.value)||fallback;input.value=value;setValue(value);this.applyPresentationChanges()};input.oninput=()=>{if(composing){setValue(input.value);void this.plugin.persistData();return}update()};input.addEventListener("compositionend",()=>{composing=false;commit()});input.onblur=commit;input.onkeydown=event=>{if(event.key==="Enter"&&!composing){event.preventDefault();commit();input.blur()}else if(event.key==="Escape"){input.value=getValue();input.blur()}}}
  private applyPresentationChanges():void{applyDerivedNodePresentation(this.model.nodes,this.model.edges,this.plugin.settings);this.minRadius=Math.min(...this.model.nodes.map(node=>node.radius));this.maxRadius=Math.max(...this.model.nodes.map(node=>node.radius));for(const node of this.model.nodes){if(node.alwaysLabel)this.ensureLabel(node);const view=this.views.get(node.id);if(view?.icon)view.icon.text=node.icon;if(view?.label&&view.labelBg)this.drawLabelBackground(view.labelBg,view.label,node.color);if(view)view.styleKey=undefined}this.lensGeometryDirty=true;void this.plugin.persistData();this.renderGraph()}
  private applyGroupChanges():void{this.plugin.settings.otherVisible=this.plugin.settings.other.visible;const before=activeNodeIds(this.model.nodes),changed:string[]=[];for(const node of this.model.nodes){const was=node.visible,role=this.searchRoles.get(node.id),searchAllowed=!this.search||role==="match"||(role==="context"&&this.plugin.settings.display.showLinkedInSearch);node.visible=searchAllowed&&nodeAllowed(node.path,this.plugin.settings.groups,this.plugin.settings.other.visible)&&isPathInFolderScope(node.path,this.folderScope);if(was!==node.visible)changed.push(node.id)}this.applyPresentationChanges();const after=activeNodeIds(this.model.nodes);if(!sameNodeIds(before,after))this.startActiveWorker();this.animateNodeVisibility(changed);this.updateGraphCount();this.createPanels();this.renderGraph()}
  private analyzeAndAutoGroup():void{const started=performance.now(),manual=this.plugin.settings.groups.filter(g=>g.origin==="manual"&&this.model.nodes.some(n=>n.path.startsWith(`${g.root}/`))),detected=inferGroups(this.model.nodes),existing=new Map(this.plugin.settings.groups.map(g=>[g.root,g]));this.pushHistory();const automatic=detected.map((fresh,i)=>{const prior=existing.get(fresh.root);return prior?{...fresh,color:prior.color,icon:prior.icon,visible:prior.visible,order:i}:fresh});this.plugin.settings.groups=[...automatic,...manual.filter(g=>!automatic.some(a=>a.root===g.root))].map((g,i)=>({...g,order:i}));this.activeLenses=new Set([...this.activeLenses].filter(path=>this.plugin.settings.groups.some(g=>g.root===path)));this.applyGroupChanges();new Notice(`Groups analyzed in ${Math.round(performance.now()-started)} ms.`)}
  private deleteAllGroups():void{const key="delete-all-groups",now=Date.now();if((this.presetOverwriteArmed.get(key)??0)<now){this.presetOverwriteArmed.set(key,now+5000);new Notice("Click Delete All Groups again within 5 seconds to confirm.");return}this.presetOverwriteArmed.delete(key);this.pushHistory();this.plugin.settings.groups=[];this.activeLenses.clear();this.applyGroupChanges();new Notice("All Groups deleted. Nodes now use Other styling.")}
  private createForcesPanel():void {this.createPanel("forces","Forces",body=>{
    const inputs=new Map<string,HTMLInputElement>(),configs=[["center","Center force",0,DEFAULT_FORCES.center,4],["repel","Repel force",0,DEFAULT_FORCES.repel,1]] as const;
    for(const [key,label,min,mid,max] of configs)inputs.set(key,this.mappedSlider(body,label,this.plugin.settings.forces[key],min,mid,max,v=>{this.plugin.settings.forces[key]=v;void this.plugin.persistData();this.updateForces()}));
    const stretch=this.slider(body,"Link stretchiness",this.plugin.settings.forces.stretchiness,-1,1,.01,v=>{this.plugin.settings.forces.stretchiness=v;void this.plugin.persistData();this.updateForces()});inputs.set("stretchiness",stretch);
    const sibling=this.toggle(body,"Sibling link force",this.plugin.settings.forces.siblingLinkForce,v=>{this.plugin.settings.forces.siblingLinkForce=v;void this.plugin.persistData();this.updateForces()});
    const advanced=body.createEl("details",{cls:"beautiful-advanced-links"});advanced.createEl("summary",{text:"Advanced links"});const advancedBody=advanced.createDiv(),linkConfigs=[["link","Link force",0,DEFAULT_FORCES.link,.2],["distance","Link distance",10,DEFAULT_FORCES.distance,500],["curvature","Link curvature",0,DEFAULT_FORCES.curvature,2]] as const;
    for(const [key,label,min,mid,max] of linkConfigs)inputs.set(key,this.mappedSlider(advancedBody,label,this.plugin.settings.forces[key],min,mid,max,v=>{this.plugin.settings.forces[key]=v;void this.plugin.persistData();this.updateForces()}));
    const sync=()=>{for(const [key,,min,mid,max] of [...configs,...linkConfigs])this.setMappedValue(inputs.get(key)!,this.plugin.settings.forces[key],min,mid,max);stretch.value=String(this.plugin.settings.forces.stretchiness);sibling.checked=this.plugin.settings.forces.siblingLinkForce};
    const reset=body.createEl("button",{cls:"beautiful-panel-reset",text:"Reset forces"});reset.onclick=()=>{this.pushHistory();this.plugin.settings.forces={...DEFAULT_FORCES};sync();void this.plugin.persistData();this.updateForces()};const tune=body.createEl("button",{cls:"beautiful-panel-reset",text:"Analyze & Tune"});tune.onclick=()=>{this.pushHistory();this.autoTuneForces();sync()};this.addPresetControls(body,"forces",sync);
  })}
  private createDisplayPanel():void {this.createPanel("display","Display",body=>{
    const inputs=new Map<string,HTMLInputElement>(),configs=[["textFade","Text fade threshold",2,DEFAULT_DISPLAY.textFade,60],["nodeSize","Node size",.2,DEFAULT_DISPLAY.nodeSize,3],["linkThickness","Link thickness",.1,DEFAULT_DISPLAY.linkThickness,6],["glow","Glow intensity",0,DEFAULT_DISPLAY.glow,2],["glowSize","Glow size",0,DEFAULT_DISPLAY.glowSize,4]] as const;
    for(const [key,label,min,mid,max] of configs)inputs.set(key,this.mappedSlider(body,label,this.plugin.settings.display[key],min,mid,max,v=>{this.plugin.settings.display[key]=v;if(key==="nodeSize")this.updateNodeScale();void this.plugin.persistData();this.renderGraph()}));
    const sibling=this.toggle(body,"Show sibling links",this.plugin.settings.display.showSiblingLinks,v=>{this.plugin.settings.display.showSiblingLinks=v;void this.plugin.persistData();this.renderGraph()});const linked=this.toggle(body,"Show linked in search",this.plugin.settings.display.showLinkedInSearch,v=>{this.plugin.settings.display.showLinkedInSearch=v;void this.plugin.persistData();if(this.search)void this.applySearch(this.search);else this.renderGraph()});const recenter=this.toggle(body,"Recenter on clicked node",this.plugin.settings.display.recenterOnFocus,v=>{this.plugin.settings.display.recenterOnFocus=v;void this.plugin.persistData()});const sync=()=>{for(const [key,,min,mid,max] of configs)this.setMappedValue(inputs.get(key)!,this.plugin.settings.display[key],min,mid,max);sibling.checked=this.plugin.settings.display.showSiblingLinks;linked.checked=this.plugin.settings.display.showLinkedInSearch;recenter.checked=this.plugin.settings.display.recenterOnFocus};
    const reset=body.createEl("button",{cls:"beautiful-panel-reset",text:"Reset display"});reset.onclick=()=>{this.pushHistory();this.plugin.settings.display={...DEFAULT_DISPLAY};sync();this.invalidateNodeStyles();this.updateNodeScale();void this.plugin.persistData();this.renderGraph()};const tune=body.createEl("button",{cls:"beautiful-panel-reset",text:"Analyze & Tune"});tune.onclick=()=>{this.pushHistory();this.autoTuneDisplay();sync()};this.addPresetControls(body,"display",sync);
  })}
  private createGuiDock():void{this.contentEl.querySelector(".beautiful-gui-dock")?.remove();const dock=this.contentEl.createDiv({cls:"beautiful-gui-dock"}),reset=dock.createEl("button",{text:"Reset GUI"}),collapse=dock.createEl("button",{cls:"beautiful-gui-collapse"});reset.onclick=()=>this.resetGui();collapse.onclick=()=>{const states=Object.values(this.plugin.settings.panels),collapseTo=!states.every(state=>state.collapsed);for(const state of states)state.collapsed=collapseTo;void this.plugin.persistData();this.createPanels();this.updateGuiDockLabel()};this.updateGuiDockLabel()}
  private updateGuiDockLabel():void{const button=this.contentEl.querySelector<HTMLButtonElement>(".beautiful-gui-collapse"),states=Object.values(this.plugin.settings.panels),all=states.length>0&&states.every(state=>state.collapsed);if(button)button.textContent=all?"Expand all":"Collapse all"}
  private resetGui():void{const marginX=Math.round(this.contentEl.clientWidth*.05),marginY=Math.round(this.contentEl.clientHeight*.05),sizes={groups:{width:245,height:520},forces:{width:247,height:378},display:{width:247,height:474}} as const;for(const [id,size] of Object.entries(sizes)){const state=this.plugin.settings.panels[id]??={visible:true,collapsed:false};state.collapsed=false;state.width=size.width;state.height=Math.min(size.height,this.contentEl.clientHeight-marginY*2);state.x=id==="display"?this.contentEl.clientWidth-marginX-size.width:marginX;state.y=id==="forces"||id==="display"?this.contentEl.clientHeight-marginY-state.height:marginY;this.plugin.settings.panels[id]=state}void this.plugin.persistData();this.createPanels();this.updateGuiDockLabel()}
  private createPanel(id:string,title:string,fill:(body:HTMLElement)=>void):void {
    const state=this.plugin.settings.panels[id]??={visible:true,collapsed:false};if(!state.collapsed&&state.height!==undefined&&state.height<=44)delete state.height;
    const panel=this.contentEl.createDiv({cls:`beautiful-graph-panel beautiful-panel-${id}`});if(state.x!==undefined){panel.style.left=`${state.x}px`;panel.style.top=`${state.y??12}px`;panel.style.right="auto";panel.style.bottom="auto"}if(state.width)panel.style.width=`${state.width}px`;if(state.height)panel.style.height=`${state.height}px`;panel.style.zIndex=String(state.z??10);panel.toggleClass("is-collapsed",state.collapsed);
    const head=panel.createDiv({cls:"beautiful-panel-head"});head.createSpan({text:title});const collapse=head.createEl("button",{cls:"beautiful-panel-collapse",text:state.collapsed?"+":"−"}),body=panel.createDiv({cls:"beautiful-panel-body"});
    collapse.onclick=e=>{e.stopPropagation();state.collapsed=!state.collapsed;if(!state.collapsed){delete state.height;panel.style.removeProperty("height")}panel.toggleClass("is-collapsed",state.collapsed);collapse.textContent=state.collapsed?"+":"−";void this.plugin.persistData();this.updateGuiDockLabel()};
    let moving=false,pointerId:number|undefined,sx=0,sy=0,ox=0,oy=0;const finish=()=>{if(!moving)return;moving=false;if(pointerId!==undefined&&head.hasPointerCapture(pointerId))head.releasePointerCapture(pointerId);pointerId=undefined;state.x=panel.offsetLeft;state.y=panel.offsetTop;void this.plugin.persistData()};
    head.onpointerdown=e=>{if(e.target===collapse)return;moving=true;pointerId=e.pointerId;sx=e.clientX;sy=e.clientY;const rect=panel.getBoundingClientRect(),host=this.contentEl.getBoundingClientRect();ox=rect.left-host.left;oy=rect.top-host.top;head.setPointerCapture(e.pointerId);state.z=++this.panelZ;panel.style.zIndex=String(state.z)};
    head.onpointermove=e=>{if(!moving)return;const x=Math.max(0,Math.min(this.contentEl.clientWidth-panel.offsetWidth,ox+e.clientX-sx)),y=Math.max(0,Math.min(this.contentEl.clientHeight-panel.offsetHeight,oy+e.clientY-sy));panel.style.left=`${x}px`;panel.style.top=`${y}px`;panel.style.right="auto";panel.style.bottom="auto"};head.onpointerup=finish;head.onpointercancel=finish;head.onlostpointercapture=finish;window.addEventListener("blur",finish,{once:true});
    panel.onpointerup=()=>{if(!state.collapsed){state.width=panel.offsetWidth;state.height=panel.offsetHeight}void this.plugin.persistData()};fill(body);
  }
  private slider(body:HTMLElement,label:string,value:number,min:number,max:number,step:number,onChange:(n:number)=>void):HTMLInputElement {const row=body.createEl("label");row.createSpan({text:label});const input=row.createEl("input",{type:"range"});input.min=String(min);input.max=String(max);input.step=String(step);input.value=String(value);input.addEventListener("pointerdown",()=>this.pushHistory());input.oninput=()=>onChange(Number(input.value));return input;}
  private mappedSlider(body:HTMLElement,label:string,value:number,min:number,mid:number,max:number,onChange:(n:number)=>void):HTMLInputElement {const input=this.slider(body,label,50,0,100,.1,p=>onChange(p<=50?min+(mid-min)*(p/50):mid+(max-mid)*((p-50)/50)));this.setMappedValue(input,value,min,mid,max);return input}
  private setMappedValue(input:HTMLInputElement,value:number,min:number,mid:number,max:number):void {input.value=String(value<=mid?50*(value-min)/Math.max(.0001,mid-min):50+50*(value-mid)/Math.max(.0001,max-mid))}
  private toggle(body:HTMLElement,label:string,value:boolean,onChange:(v:boolean)=>void):HTMLInputElement {const row=body.createEl("label");row.createSpan({text:label});const input=row.createEl("input",{type:"checkbox"});input.checked=value;input.onchange=()=>{this.pushHistory();onChange(input.checked)};return input}
  private addPresetControls(body:HTMLElement,kind:"forces"|"display",sync:()=>void):void {
    const row=body.createDiv({cls:"beautiful-preset-row"}),nameInput=row.createEl("input",{type:"text",placeholder:"Name custom preset..."}),list=row.createEl("datalist"),presets=kind==="forces"?this.plugin.settings.forcePresets:this.plugin.settings.displayPresets,id=`beautiful-${kind}-presets-${Math.random().toString(36).slice(2)}`;nameInput.setAttr("list",id);list.id=id;
    const refresh=(selected?:string)=>{list.empty();for(const name of Object.keys(presets).sort())list.createEl("option",{value:name});if(selected)nameInput.value=selected};refresh();
    row.createEl("button",{text:"Load"}).onclick=()=>{const name=nameInput.value.trim();if(!name||!Object.prototype.hasOwnProperty.call(presets,name))return;this.pushHistory();if(kind==="forces"){this.plugin.settings.forces={...DEFAULT_FORCES,...this.plugin.settings.forcePresets[name]};this.updateForces()}else{this.plugin.settings.display={...DEFAULT_DISPLAY,...this.plugin.settings.displayPresets[name]};this.invalidateNodeStyles();this.updateNodeScale();this.renderGraph()}sync();void this.plugin.persistData()};
    row.createEl("button",{text:"Save preset"}).onclick=()=>{const name=nameInput.value.trim();if(!name){new Notice("Enter a preset name first.");return}const key=`${kind}:${name}`,exists=Object.prototype.hasOwnProperty.call(presets,name),now=Date.now();if(exists&&(this.presetOverwriteArmed.get(key)??0)<now){this.presetOverwriteArmed.set(key,now+5000);new Notice(`Preset “${name}” exists. Click Save preset again within 5 seconds to overwrite.`);return}this.presetOverwriteArmed.delete(key);this.pushHistory();if(kind==="forces")this.plugin.settings.forcePresets[name]=structuredClone(this.plugin.settings.forces);else this.plugin.settings.displayPresets[name]=structuredClone(this.plugin.settings.display);refresh(name);void this.plugin.persistData();new Notice(`${kind==="forces"?"Forces":"Display"} preset “${name}” ${exists?"updated":"saved"}.`);this.focusSearchSoon()};
    row.createEl("button",{text:"Delete"}).onclick=()=>{const name=nameInput.value.trim();if(!name||!Object.prototype.hasOwnProperty.call(presets,name)){new Notice("Select a saved preset first.");return}const key=`delete:${kind}:${name}`,now=Date.now();if((this.presetOverwriteArmed.get(key)??0)<now){this.presetOverwriteArmed.set(key,now+5000);new Notice(`Click Delete again within 5 seconds to remove “${name}”.`);return}this.presetOverwriteArmed.delete(key);this.pushHistory();delete presets[name];nameInput.value="";refresh();void this.plugin.persistData();new Notice(`Preset “${name}” deleted.`)};
  }
  private bindNavigation(host:HTMLElement):void {let panning=false,last={x:0,y:0};host.oncontextmenu=e=>{if(e.button===1)e.preventDefault()};host.onpointerdown=e=>{if(e.button===0)this.unpinFocus();if((e.button===0&&!this.dragged)||e.button===1){e.preventDefault();panning=true;last={x:e.clientX,y:e.clientY};host.setPointerCapture(e.pointerId)}};host.onpointermove=e=>{const rect=host.getBoundingClientRect();if(this.hovered){const gx=(e.clientX-rect.left-this.offset.x)/this.scale,gy=(e.clientY-rect.top-this.offset.y)/this.scale,r=this.hovered.radius*this.plugin.settings.display.nodeSize+6/this.scale;if(Math.hypot(gx-this.hovered.x,gy-this.hovered.y)>r)this.clearHover()}if(this.dragged&&(e.buttons&1)){panning=false;const x=(e.clientX-rect.left-this.offset.x)/this.scale,y=(e.clientY-rect.top-this.offset.y)/this.scale;this.dragged.x=x;this.dragged.y=y;this.worker?.postMessage({type:"drag",id:this.dragged.id,x,y});this.queueRender();return}if(!panning)return;this.zoomTarget=undefined;this.offset.x+=e.clientX-last.x;this.offset.y+=e.clientY-last.y;last={x:e.clientX,y:e.clientY};this.applyCameraTransform()};host.onpointerup=e=>{if(e.button===0||e.button===1)panning=false;if(e.button===0)this.releaseNode()};host.onpointerleave=()=>{panning=false;this.cancelHoverIntent();this.releaseNode();this.clearHover()};host.onwheel=e=>{e.preventDefault();this.clearHoverImmediate();const rect=host.getBoundingClientRect(),px=e.clientX-rect.left,py=e.clientY-rect.top,target=Math.max(.08,Math.min(5,(this.zoomTarget?.scale??this.scale)*Math.exp(-e.deltaY*.001)));const base=this.zoomTarget??{scale:this.scale,x:this.offset.x,y:this.offset.y},gx=(px-base.x)/base.scale,gy=(py-base.y)/base.scale;this.zoomTarget={scale:target,x:px-gx*target,y:py-gy*target};this.animateZoom()};}
  private applyCameraTransform():void {this.world.position.set(this.offset.x,this.offset.y);this.world.scale.set(this.scale);this.focusWorld.position.set(this.offset.x,this.offset.y);this.focusWorld.scale.set(this.scale);const neighbors=this.hovered?this.adjacency.get(this.hovered.id):undefined;for(const view of this.views.values())if(view.label)this.updateNodeView(view,!this.hovered||view.node.id===this.hovered.id||neighbors?.has(view.node.id)===true);this.layoutLabels()}
  private animateZoom():void {if(this.zoomAnimating)return;this.zoomAnimating=true;let last=performance.now();const step=(now:number)=>{if(!this.zoomTarget){this.zoomAnimating=false;return}const dt=Math.min(50,Math.max(1,now-last));last=now;const t=this.zoomTarget,blend=1-Math.exp(-dt/160);this.scale+=(t.scale-this.scale)*blend;this.offset.x+=(t.x-this.offset.x)*blend;this.offset.y+=(t.y-this.offset.y)*blend;this.applyCameraTransform();if(Math.abs(t.scale-this.scale)>.001||Math.hypot(t.x-this.offset.x,t.y-this.offset.y)>.2)requestAnimationFrame(step);else{this.scale=t.scale;this.offset={x:t.x,y:t.y};this.zoomTarget=undefined;this.zoomAnimating=false;this.renderGraph()}};requestAnimationFrame(step)}
  private setCategoryVisible(category:string,shown:boolean):void {this.pushHistory();this.plugin.settings.categoryVisibility[category]=shown;const changed:string[]=[];for(const node of this.model.nodes)if(node.category===category){const visible=shown&&isPathInFolderScope(node.path,this.folderScope);if(node.visible!==visible)changed.push(node.id);node.visible=visible}this.lensGeometryDirty=true;void this.plugin.persistData();if(this.search){void this.applySearch(this.search)}else{this.startActiveWorker();this.animateNodeVisibility(changed)}this.updateGraphCount();this.createPanels()}
  private makeObstacleGrid():Map<string,GraphNode[]>{const size=60,g=new Map<string,GraphNode[]>();for(const n of this.model.nodes)if(n.visible){const k=`${Math.floor(n.x/size)},${Math.floor(n.y/size)}`;const a=g.get(k)??[];a.push(n);g.set(k,a)}return g}
  private edgeBend(a:GraphNode,b:GraphNode,g:Map<string,GraphNode[]>):number {const size=60,dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(len<20)return 0;let pressure=0;const seen=new Set<string>();for(const sample of [.2,.35,.5,.65,.8]){const cx=Math.floor((a.x+dx*sample)/size),cy=Math.floor((a.y+dy*sample)/size);for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const n of g.get(`${cx+ox},${cy+oy}`)??[]){if(n===a||n===b||seen.has(n.id))continue;seen.add(n.id);const t=((n.x-a.x)*dx+(n.y-a.y)*dy)/(len*len);if(t<.08||t>.92)continue;const side=((n.x-a.x)*dy-(n.y-a.y)*dx)/len,clearance=n.radius+14;if(Math.abs(side)<clearance)pressure+=(side>=0?-1:1)*(1-Math.abs(side)/clearance)}}return Math.max(-.34,Math.min(.34,pressure*.16))}
  private invalidateNodeStyles():void {for(const view of this.views.values())view.styleKey=undefined}
  private pushHistory():void {this.history.push(structuredClone(this.plugin.settings));const limit=Math.max(10,this.plugin.settings.historyLimit||50);if(this.history.length>limit)this.history.splice(0,this.history.length-limit)}
  private undoSettings():void {const previous=this.history.pop();if(!previous)return;this.plugin.settings=previous;void this.plugin.persistData();this.rebuild(true);this.createPanels()}
  private updateNodeScale():void {this.invalidateNodeStyles();this.lensGeometryDirty=true;this.worker?.postMessage({type:"nodeScale",value:this.plugin.settings.display.nodeSize})}
  private analyzedForceProfile():BeautifulGraphSettings["forces"]|undefined {const nodes=this.model.nodes.filter(n=>n.visible),visibleIds=new Set(nodes.map(n=>n.id));if(!nodes.length)return;const edgeCount=this.model.edges.reduce((n,e)=>n+Number(visibleIds.has(e.source)&&visibleIds.has(e.target)),0),avgDegree=edgeCount*2/nodes.length,sizeFactor=Math.max(.72,Math.min(1.32,Math.sqrt(1430/nodes.length))),degreeFactor=Math.max(.82,Math.min(1.18,Math.sqrt(3.2/Math.max(.5,avgDegree))));return{...this.plugin.settings.forces,center:Number((DEFAULT_FORCES.center/Math.sqrt(sizeFactor)).toFixed(3)),repel:Number((DEFAULT_FORCES.repel*sizeFactor).toFixed(3)),link:Number((DEFAULT_FORCES.link*degreeFactor).toFixed(3)),distance:Math.round(DEFAULT_FORCES.distance*Math.max(.78,Math.min(1.25,sizeFactor)))}}
  private applyAnalyzedForceProfile():void {const profile=this.analyzedForceProfile();if(!profile)return;this.plugin.settings.forces=profile;void this.plugin.persistData()}
  private autoTuneForces():void {this.applyAnalyzedForceProfile();this.updateForces(true);new Notice("Forces analyzed. Running a full convergence pass…")}

  private scheduleModelRefresh():void {if(this.modelRefreshTimer)window.clearTimeout(this.modelRefreshTimer);this.modelRefreshTimer=window.setTimeout(()=>{this.modelRefreshTimer=undefined;for(const n of this.model.nodes)this.plugin.data.positions[n.path]={x:n.x,y:n.y};this.rebuild(true);this.createPanels();this.updateBreadcrumb();this.updateGraphCount()},350)}
  private autoTuneDisplay():void {const count=Math.max(1,this.model.nodes.filter(n=>n.visible).length),area=Math.max(1,this.contentEl.clientWidth*this.contentEl.clientHeight),density=Math.max(.65,Math.min(1.45,Math.sqrt((count/1430)*(2073600/area))));this.plugin.settings.display={...this.plugin.settings.display,textFade:Math.round(Math.max(14,Math.min(40,DEFAULT_DISPLAY.textFade*Math.sqrt(density)))),nodeSize:Number(Math.max(.45,Math.min(1.2,DEFAULT_DISPLAY.nodeSize/Math.sqrt(density))).toFixed(2)),linkThickness:Number(Math.max(.4,Math.min(1.4,DEFAULT_DISPLAY.linkThickness/Math.sqrt(density))).toFixed(2)),glow:DEFAULT_DISPLAY.glow,glowSize:DEFAULT_DISPLAY.glowSize};this.invalidateNodeStyles();this.updateNodeScale();void this.plugin.persistData();this.renderGraph()}
  private releaseNode():void {if(!this.dragged)return;this.worker?.postMessage({type:"release",id:this.dragged.id});this.dragged=undefined;}
  private focusNode(node:GraphNode):void {const targetScale=Math.max(1,this.scale);this.zoomTarget={scale:targetScale,x:this.contentEl.clientWidth/2-node.x*targetScale,y:this.contentEl.clientHeight/2-node.y*targetScale};this.animateZoom();}
  private fit():void {const nodes=this.model.nodes.filter(n=>n.visible&&Number.isFinite(n.x)&&Number.isFinite(n.y));if(!nodes.length)return;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const n of nodes){minX=Math.min(minX,n.x);maxX=Math.max(maxX,n.x);minY=Math.min(minY,n.y);maxY=Math.max(maxY,n.y)}const width=Math.max(100,maxX-minX),height=Math.max(100,maxY-minY),availableW=Math.max(300,this.contentEl.clientWidth-560),availableH=Math.max(250,this.contentEl.clientHeight-180),scale=Math.max(.06,Math.min(1.25,availableW/width,availableH/height)*.9);this.zoomTarget={scale,x:this.contentEl.clientWidth/2-(minX+maxX)/2*scale,y:this.contentEl.clientHeight/2-(minY+maxY)/2*scale};this.animateZoom();}
  private showTooltip(n:GraphNode):void {let tip=this.contentEl.querySelector<HTMLElement>(".beautiful-graph-tooltip");if(!tip)tip=this.contentEl.createDiv({cls:"beautiful-graph-tooltip"});tip.empty();tip.createDiv({cls:"beautiful-tooltip-title",text:n.label});tip.createDiv({cls:"beautiful-tooltip-meta",text:`${n.category} · ${n.degree} connections`});const path=tip.createDiv({cls:"beautiful-tooltip-path",text:formatTooltipPath(n.path)});path.title=this.prettyPath(n.path);if(n.description)tip.createDiv({cls:"beautiful-tooltip-description",text:n.description});tip.show();}
  private prettyPath(path:string):string{return path.replaceAll("_"," ").split("/").map(part=>part.replace(/\b[a-z]/g,c=>c.toUpperCase())).join("  >  ")}
  private hideTooltip():void {this.contentEl.querySelector<HTMLElement>(".beautiful-graph-tooltip")?.hide();}
  private contextMenu(node:GraphNode,x:number,y:number):void {const menu=new Menu();menu.addItem(i=>i.setTitle("Open note").onClick(()=>this.openNode(node)));if(node.path.endsWith("/index.md")&&node.folder&&!this.plugin.settings.groups.some(g=>g.root===node.folder))menu.addItem(i=>i.setTitle("Create Group from folder").setIcon("folder-plus").onClick(()=>{this.pushHistory();this.plugin.settings.groups.push(this.makeManualGroup(node.folder));this.applyGroupChanges()}));menu.showAtPosition({x,y});}
  private openNode(node:GraphNode):void {const file=this.app.vault.getAbstractFileByPath(node.path);if(file instanceof TFile)void this.app.workspace.getLeaf(false).openFile(file)}
  private openNodeInTab(node:GraphNode):void {const file=this.app.vault.getAbstractFileByPath(node.path);if(file instanceof TFile)void this.app.workspace.getLeaf("tab").openFile(file)}
  private savePositions():void {for(const n of this.model.nodes)this.plugin.data.positions[n.path]={x:n.x,y:n.y};void this.plugin.persistData();}
}
