export function createPhysicsWorker(): Worker {
  const source = `
    let nodes=[], edges=[], opts={center:.25,repel:.5,link:.5,distance:100,curvature:0,stretchiness:0,siblingLinkForce:true}, timer, alpha=1, quiet=0, nodeScale=1, routeSides=new Map(), adjacency=new Map(), searchRoles=new Map(), stepNo=0;
    const byId=()=>new Map(nodes.map(n=>[n.id,n]));
    onmessage=e=>{const m=e.data;
      if(m.type==='init'){nodes=m.nodes.map(n=>({...n,vx:0,vy:0,fx:null,fy:null}));edges=m.edges;opts=m.opts;nodeScale=m.nodeScale||1;routeSides=new Map();adjacency=new Map();for(const e of edges){if(!adjacency.has(e.source))adjacency.set(e.source,[]);if(!adjacency.has(e.target))adjacency.set(e.target,[]);adjacency.get(e.source).push(e.target);adjacency.get(e.target).push(e.source)}stepNo=0;run(1,true)}
      else if(m.type==='forces'){opts=m.opts;run(1,!!m.thorough)}
      else if(m.type==='groups'){const groups=new Map(m.groups);for(const n of nodes)n.group=groups.get(n.id)??n.folder;run(.8)}
      else if(m.type==='visibility'){const ids=new Set(m.ids);for(const n of nodes)if(ids.has(n.id))n.visible=m.visible;run(.65)}
      else if(m.type==='searchRoles'){searchRoles=new Map(m.roles);run(.75)}
      else if(m.type==='nodeScale'){nodeScale=m.value||1;run(.7)}
      else if(m.type==='drag'){const n=byId().get(m.id);if(n){n.fx=m.x;n.fy=m.y;n.x=m.x;n.y=m.y;n.vx=0;n.vy=0;run(.45)}}
      else if(m.type==='release'){const n=byId().get(m.id);if(n){n.fx=null;n.fy=null;run(.35)}}
    };
    function run(heat,thorough=false){alpha=Math.max(alpha,heat);quiet=0;clearInterval(timer);const substeps=thorough?6:2,decay=thorough?.978:.96,minAlpha=thorough?.006:.02;let publish=0;timer=setInterval(()=>{let energy=0;for(let i=0;i<substeps;i++)energy=step(i===substeps-1);if(!thorough||publish++%2===0)postMessage({type:'tick',nodes:nodes.map(n=>({id:n.id,x:n.x,y:n.y}))});alpha*=decay;if(alpha<minAlpha&&energy<(thorough?.003:.008)){quiet++;if(quiet>(thorough?28:18)){clearInterval(timer);postMessage({type:'settled',nodes:nodes.map(n=>({id:n.id,x:n.x,y:n.y}))})}}else quiet=0},16)}
    function tree(points){
      let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const n of points){minX=Math.min(minX,n.x);minY=Math.min(minY,n.y);maxX=Math.max(maxX,n.x);maxY=Math.max(maxY,n.y)}
      const size=Math.max(1,maxX-minX,maxY-minY),root={x:minX,y:minY,size,items:[],kids:null,cx:0,cy:0,count:0};
      function insert(q,n,depth){q.count++;q.cx+=(n.x-q.cx)/q.count;q.cy+=(n.y-q.cy)/q.count;if(!q.kids&&(q.items.length<4||depth>16)){q.items.push(n);return}if(!q.kids){q.kids=[0,1,2,3].map(i=>({x:q.x+(i%2)*q.size/2,y:q.y+(i>1?q.size/2:0),size:q.size/2,items:[],kids:null,cx:0,cy:0,count:0}));for(const old of q.items)insert(q.kids[(old.x>=q.x+q.size/2?1:0)+(old.y>=q.y+q.size/2?2:0)],old,depth+1);q.items=[]}insert(q.kids[(n.x>=q.x+q.size/2?1:0)+(n.y>=q.y+q.size/2?2:0)],n,depth+1)}
      for(const n of points)insert(root,n,0);return root;
    }
    function repel(n,q){if(!q.count)return;const dx=q.cx-n.x,dy=q.cy-n.y,d2=dx*dx+dy*dy+.01;if(!q.kids){for(const b of q.items){if(b===n)continue;const x=b.x-n.x,y=b.y-n.y,r2=x*x+y*y+36,f=alpha*opts.repel*14/r2;n.vx-=x*f;n.vy-=y*f}return}if(q.size*q.size/d2<.55){const f=alpha*opts.repel*14*q.count/Math.max(36,d2);n.vx-=dx*f;n.vy-=dy*f;return}for(const k of q.kids)repel(n,k)}
    function separateAngles(map){for(const [id,ids] of adjacency){const hub=map.get(id);if(!hub||ids.length<2)continue;const ns=ids.map(x=>map.get(x)).filter(Boolean).map(n=>({n,a:Math.atan2(n.y-hub.y,n.x-hub.x)})).sort((a,b)=>a.a-b.a),desired=Math.min(.7,Math.PI*2/ns.length);for(let i=0;i<ns.length;i++){const left=ns[i],right=ns[(i+1)%ns.length],gap=((right.a-left.a+Math.PI*2)%(Math.PI*2));if(gap>=desired)continue;const push=(desired-gap)*opts.curvature*.055*alpha,la=left.a,ra=right.a;left.n.vx+=Math.sin(la)*push;left.n.vy-=Math.cos(la)*push;right.n.vx-=Math.sin(ra)*push;right.n.vy+=Math.cos(ra)*push}}}
    function resolvePositions(visible){const maxR=Math.max(4,...visible.map(n=>(n.radius||4)*nodeScale)),size=maxR*2+12;for(let pass=0;pass<3;pass++){const grid=new Map();for(const n of visible){const key=Math.floor(n.x/size)+','+Math.floor(n.y/size);if(!grid.has(key))grid.set(key,[]);grid.get(key).push(n)}for(const a of visible){const cx=Math.floor(a.x/size),cy=Math.floor(a.y/size);for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const b of grid.get((cx+ox)+','+(cy+oy))||[]){if(a.id>=b.id)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=((a.radius||4)+(b.radius||4))*nodeScale+10;if(d>=min)continue;if(d<.001){const seed=(a.id.length*31+b.id.length*17)%628,angle=seed/100;dx=Math.cos(angle);dy=Math.sin(angle);d=1}const nx=dx/d,ny=dy/d,overlap=min-d,ma=Math.max(1,Math.pow((a.radius||4)*nodeScale,2)),mb=Math.max(1,Math.pow((b.radius||4)*nodeScale,2));let wa=a.fx!=null?0:mb/(ma+mb),wb=b.fx!=null?0:ma/(ma+mb);const ar=searchRoles.get(a.id),br=searchRoles.get(b.id);if(ar==='match'&&br==='context'){wa=0;wb=1}else if(ar==='context'&&br==='match'){wa=1;wb=0}if(wa===0&&wb===0)continue;if(wa===0)wb=1;if(wb===0)wa=1;a.x-=nx*overlap*wa;a.y-=ny*overlap*wa;b.x+=nx*overlap*wb;b.y+=ny*overlap*wb;const closing=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(closing<0){const impulse=-closing*.55;a.vx-=nx*impulse*wa;a.vy-=ny*impulse*wa;b.vx+=nx*impulse*wb;b.vy+=ny*impulse*wb}}}}}
    function step(project){const visible=nodes.filter(n=>n.visible),map=new Map(visible.map(n=>[n.id,n])),searchMode=searchRoles.size>0,core=searchMode?visible.filter(n=>searchRoles.get(n.id)==='match'):visible,satellites=searchMode?visible.filter(n=>searchRoles.get(n.id)==='context'):[],coreRoot=tree(core),satelliteRoot=satellites.length?tree(satellites):coreRoot,maxR=Math.max(4,...visible.map(n=>(n.radius||4)*nodeScale)),cellSize=Math.max(24,opts.distance*.3,maxR*2+12),grid=new Map();
      let coreX=0,coreY=0;for(const n of core){coreX+=n.x;coreY+=n.y}coreX/=Math.max(1,core.length);coreY/=Math.max(1,core.length);let coreRms=0;for(const n of core)coreRms+=(n.x-coreX)*(n.x-coreX)+(n.y-coreY)*(n.y-coreY);coreRms=Math.sqrt(coreRms/Math.max(1,core.length));const rimRadius=Math.max(opts.distance*2.5,coreRms*1.55+opts.distance*1.15);
      for(const e of edges){const a=map.get(e.source),b=map.get(e.target),ar=searchRoles.get(e.source),br=searchRoles.get(e.target);if(!a||!b||!((ar==='context')!==(br==='context')))continue;const satellite=ar==='context'?a:b,anchor=ar==='context'?b:a,dx=anchor.x-satellite.x,dy=anchor.y-satellite.y,d=Math.hypot(dx,dy)||1,extension=d-opts.distance*3,f=extension*.00115*opts.link*11*alpha;satellite.vx+=dx*f;satellite.vy+=dy*f}
      const folderCenters=new Map(),centerNodes=searchMode?core:visible;for(const n of centerNodes){const group=n.group??n.folder;let f=folderCenters.get(group);if(!f)folderCenters.set(group,f={id:group,x:0,y:0,count:0,fx:0,fy:0});f.x+=n.x;f.y+=n.y;f.count++}for(const f of folderCenters.values()){f.x/=f.count;f.y/=f.count}const major=[...folderCenters.values()].filter(f=>f.count>=Math.max(8,centerNodes.length*.008));for(let i=0;i<major.length;i++)for(let j=i+1;j<major.length;j++){const a=major[i],b=major[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,unit=Math.max(8,opts.distance*.06),desired=(Math.sqrt(a.count)+Math.sqrt(b.count))*unit;if(d>=desired)continue;const push=(1-d/desired)*.075*alpha,nx=dx/d,ny=dy/d;a.fx-=nx*push;a.fy-=ny*push;b.fx+=nx*push;b.fy+=ny*push}
      for(const n of visible){const f=folderCenters.get(n.group??n.folder),role=searchRoles.get(n.id);if(searchMode&&role==='context'){const dx=n.x-coreX,dy=n.y-coreY,d=Math.hypot(dx,dy)||1,radial=(rimRadius-d)*.012*alpha;n.vx=(n.vx||0)*.72+dx/d*radial;n.vy=(n.vy||0)*.72+dy/d*radial;repel(n,satelliteRoot)}else{n.vx=(n.vx||0)*.72+alpha*(-n.x*.006*opts.center+(f.x-n.x)*.00028)+f.fx;n.vy=(n.vy||0)*.72+alpha*(-n.y*.006*opts.center+(f.y-n.y)*.00028)+f.fy;repel(n,coreRoot)}const key=Math.floor(n.x/cellSize)+','+Math.floor(n.y/cellSize);if(!grid.has(key))grid.set(key,[]);grid.get(key).push(n)}
      for(const a of visible){const cx=Math.floor(a.x/cellSize),cy=Math.floor(a.y/cellSize);for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const b of grid.get((cx+ox)+','+(cy+oy))||[]){if(a.id>=b.id)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.1,min=((a.radius||4)+(b.radius||4))*nodeScale+10;if(d<min){const f=(min-d)/d*.6*alpha;a.vx-=dx*f;a.vy-=dy*f;b.vx+=dx*f;b.vy+=dy*f}}}
      for(const e of edges){const a=map.get(e.source),b=map.get(e.target);if(!a||!b||(searchMode&&(searchRoles.get(a.id)==='context'||searchRoles.get(b.id)==='context'))||(opts.siblingLinkForce===false&&a.folder===b.folder))continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,stretch=opts.stretchiness||0,extension=d-opts.distance,slack=stretch>0?opts.distance*stretch*.45:0,elastic=stretch>=0?Math.sign(extension)*Math.max(0,Math.abs(extension)-slack)*(1+stretch*Math.min(2,Math.abs(extension)/Math.max(1,opts.distance))):extension*(1-stretch*2),f=elastic*.00115*opts.link*alpha;a.vx+=dx*f;a.vy+=dy*f;b.vx-=dx*f;b.vy-=dy*f;if(opts.curvature>0){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2,cx=Math.floor(mx/cellSize),cy=Math.floor(my/cellSize),key=e.source+'\\0'+e.target;for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const n of grid.get((cx+ox)+','+(cy+oy))||[]){if(n===a||n===b)continue;const t=((n.x-a.x)*dx+(n.y-a.y)*dy)/(d*d);if(t<.15||t>.85)continue;const side=((n.x-a.x)*dy-(n.y-a.y)*dx)/d,clear=(n.radius||4)*nodeScale+14;if(Math.abs(side)<clear){let route=routeSides.get(key);if(route==null){route=side>=0?-1:1;routeSides.set(key,route)}const push=(1-Math.abs(side)/clear)*opts.curvature*.2*alpha*route,nx=dy/d,ny=-dx/d;a.vx+=nx*push;a.vy+=ny*push;b.vx+=nx*push;b.vy+=ny*push}}}}
      if(opts.curvature>0&&stepNo++%6===0)separateAngles(map);let energy=0;for(const n of visible){if(n.fx!=null){n.x=n.fx;n.y=n.fy;n.vx=0;n.vy=0;continue}const speed=Math.hypot(n.vx,n.vy);if(speed>8){n.vx=n.vx/speed*8;n.vy=n.vy/speed*8}if(speed<.003){n.vx=0;n.vy=0}n.x+=n.vx;n.y+=n.vy;energy+=n.vx*n.vx+n.vy*n.vy;if(!Number.isFinite(n.x)||Math.abs(n.x)>100000){n.x=0;n.y=0;n.vx=0;n.vy=0}}if(project)resolvePositions(visible);return energy/Math.max(1,visible.length)}
  `;
  return new Worker(URL.createObjectURL(new Blob([source], { type: "text/javascript" })));
}
