import { centerAcceleration, repelFactor } from "./center-force";
import { degreeNormalizedSpringStrength, springExtension } from "./spring-force";

export function createPhysicsWorker(): Worker {
  const source = `
    const centerForce=${centerAcceleration.toString()};
    const repelScale=${repelFactor.toString()};
    const springExtension=${springExtension.toString()};
    const degreeSpring=${degreeNormalizedSpringStrength.toString()};
    let nodes=[],edges=[],opts={center:1.23589544,repel:1,link:.041472,distance:362.874,curvature:0,stretchiness:.08224,siblingLinkForce:1};
    let timer,alpha=1,quiet=0,nodeScale=1,routeSides=new Map(),adjacency=new Map(),searchRoles=new Map(),stepNo=0,generation=0,publishStep=0,components=[];
    const byId=()=>new Map(nodes.map(n=>[n.id,n]));
    onmessage=e=>{const m=e.data;
      if(m.type==='init'){
        generation=m.generation||0;nodes=m.nodes.map((n,index)=>({...n,index,vx:0,vy:0,fx:null,fy:null}));edges=m.edges;opts=m.opts;nodeScale=m.nodeScale||1;routeSides=new Map();rebuildTopology();stepNo=0;publishStep=0;
        const heat=m.heat??1;if(heat>0)run(heat,m.thorough!==false);else publish('settled');
      }else if(m.type==='forces'){opts=m.opts;run(1,!!m.thorough)}
      else if(m.type==='searchRoles'){searchRoles=new Map(m.roles);run(.75)}
      else if(m.type==='nodeScale'){
        nodeScale=Math.max(.01,m.value||1);const visible=nodes.filter(n=>n.visible!==false),passes=m.final?24:4,epsilon=Math.max(0,m.epsilonWorld||0);resolvePositions(visible,passes,epsilon);for(const n of visible){n.vx=0;n.vy=0}publish('projection',{scaleGeneration:m.scaleGeneration||0});
      }else if(m.type==='dragStart'){const n=byId().get(m.id);if(n){n.fx=m.x;n.fy=m.y;n.x=m.x;n.y=m.y;n.vx=0;n.vy=0;run(.45)}}
      else if(m.type==='dragMove'){const n=byId().get(m.id);if(n){n.fx=m.x;n.fy=m.y;n.x=m.x;n.y=m.y;n.vx=0;n.vy=0;if(!timer)run(.2);else alpha=Math.max(alpha,.12)}}
      else if(m.type==='dragEnd'){const n=byId().get(m.id);if(n){n.fx=null;n.fy=null;run(.85)}}
    };
    function publish(type,extra={}){const coords=new Float32Array(nodes.length*2);for(const n of nodes){coords[n.index*2]=n.x;coords[n.index*2+1]=n.y}postMessage({type,generation,coords,...extra},[coords.buffer])}
    function run(heat,thorough=false){alpha=Math.max(alpha,heat);quiet=0;if(timer)clearInterval(timer);const substeps=thorough?6:2,decay=thorough?.978:.96,minAlpha=thorough?.006:.02;timer=setInterval(()=>{let energy=0;for(let i=0;i<substeps;i++)energy=step(i===substeps-1);if(publishStep++%2===0)publish('tick');alpha*=decay;if(alpha<minAlpha&&energy<(thorough?.003:.008)){quiet++;if(quiet>(thorough?28:18)){const metrics=layoutMetrics(nodes.filter(n=>n.visible!==false));if(metrics.accepted){clearInterval(timer);timer=undefined;publish('settled',{metrics})}else{alpha=Math.max(alpha,.12);quiet=0;publish('preview',{metrics})}}}else quiet=0},16)}
    function rebuildTopology(){adjacency=new Map(nodes.map(n=>[n.id,[]]));for(const e of edges){if(adjacency.has(e.source)&&adjacency.has(e.target)){adjacency.get(e.source).push(e.target);adjacency.get(e.target).push(e.source)}}const map=byId(),seen=new Set();components=[];for(const n of nodes){if(seen.has(n.id))continue;const ids=[],queue=[n.id];seen.add(n.id);while(queue.length){const id=queue.shift(),current=map.get(id);if(current)ids.push(current);for(const next of adjacency.get(id)||[])if(!seen.has(next)){seen.add(next);queue.push(next)}}ids.sort((a,b)=>a.id.localeCompare(b.id));components.push({key:ids[0]?.id||'',nodes:ids})}components.sort((a,b)=>b.nodes.length-a.nodes.length||a.key.localeCompare(b.key));for(let i=0;i<components.length;i++)for(const n of components[i].nodes)n.component=i}
    function hashAngle(value){let h=2166136261;for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619);return((h>>>0)/4294967296)*Math.PI*2}
    function occupiedEnvelope(visible){let area=0;for(const n of visible){const r=(n.radius||4)*nodeScale+5;area+=r*r}return Math.max(opts.distance*1.2,Math.sqrt(area/.28))}
    function componentForces(visible,graphCenter,envelope){const visibleIds=new Set(visible.map(n=>n.id)),result=new Map();for(let index=0;index<components.length;index++){const members=components[index].nodes.filter(n=>visibleIds.has(n.id));if(!members.length)continue;let x=0,y=0;for(const n of members){x+=n.x;y+=n.y}x/=members.length;y/=members.length;let tx=graphCenter.x,ty=graphCenter.y;if(index>0){const angle=hashAngle(components[index].key),ring=Math.floor(Math.sqrt(index-1)),radius=envelope*(.68+Math.min(.62,ring*.07));tx+=Math.cos(angle)*radius;ty+=Math.sin(angle)*radius}let dx=(tx-x)*.0018*opts.center,dy=(ty-y)*.0018*opts.center,m=Math.hypot(dx,dy);if(m>.42){dx=dx/m*.42;dy=dy/m*.42}result.set(index,{x:dx,y:dy})}return result}
    function tree(points){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const n of points){minX=Math.min(minX,n.x);minY=Math.min(minY,n.y);maxX=Math.max(maxX,n.x);maxY=Math.max(maxY,n.y)}if(!points.length)return{x:0,y:0,size:1,items:[],kids:null,cx:0,cy:0,count:0};const size=Math.max(1,maxX-minX,maxY-minY),root={x:minX,y:minY,size,items:[],kids:null,cx:0,cy:0,count:0};function insert(q,n,depth){q.count++;q.cx+=(n.x-q.cx)/q.count;q.cy+=(n.y-q.cy)/q.count;if(!q.kids&&(q.items.length<4||depth>16)){q.items.push(n);return}if(!q.kids){q.kids=[0,1,2,3].map(i=>({x:q.x+(i%2)*q.size/2,y:q.y+(i>1?q.size/2:0),size:q.size/2,items:[],kids:null,cx:0,cy:0,count:0}));for(const old of q.items)insert(q.kids[(old.x>=q.x+q.size/2?1:0)+(old.y>=q.y+q.size/2?2:0)],old,depth+1);q.items=[]}insert(q.kids[(n.x>=q.x+q.size/2?1:0)+(n.y>=q.y+q.size/2?2:0)],n,depth+1)}for(const n of points)insert(root,n,0);return root}
    function repel(n,q){if(!q.count)return;const dx=q.cx-n.x,dy=q.cy-n.y,d2=dx*dx+dy*dy+.01;if(!q.kids){for(const b of q.items){if(b===n)continue;const x=b.x-n.x,y=b.y-n.y,r2=x*x+y*y+36,f=repelScale(r2,1,opts.repel,alpha);n.vx-=x*f;n.vy-=y*f}return}if(q.size*q.size/d2<.55){const f=repelScale(d2,q.count,opts.repel,alpha);n.vx-=dx*f;n.vy-=dy*f;return}for(const k of q.kids)repel(n,k)}
    function separateAngles(map){const magnitude=Math.abs(opts.curvature),direction=Math.sign(opts.curvature)||1;for(const [id,ids] of adjacency){const hub=map.get(id);if(!hub||ids.length<2)continue;const ns=ids.map(x=>map.get(x)).filter(Boolean).map(n=>({n,a:Math.atan2(n.y-hub.y,n.x-hub.x)})).sort((a,b)=>a.a-b.a),desired=Math.min(.7,Math.PI*2/ns.length);for(let i=0;i<ns.length;i++){const left=ns[i],right=ns[(i+1)%ns.length],gap=((right.a-left.a+Math.PI*2)%(Math.PI*2));if(gap>=desired)continue;const push=(desired-gap)*magnitude*.055*alpha*direction,la=left.a,ra=right.a;left.n.vx+=Math.sin(la)*push;left.n.vy-=Math.cos(la)*push;right.n.vx-=Math.sin(ra)*push;right.n.vy+=Math.cos(ra)*push}}}
    function resolvePositions(visible,passes=3,epsilon=0){const maxR=Math.max(4,...visible.map(n=>(n.radius||4)*nodeScale)),size=maxR*2+12;let maximum=0;for(let pass=0;pass<passes;pass++){maximum=0;const grid=new Map();for(const n of visible){const key=Math.floor(n.x/size)+','+Math.floor(n.y/size);if(!grid.has(key))grid.set(key,[]);grid.get(key).push(n)}for(const a of visible){const cx=Math.floor(a.x/size),cy=Math.floor(a.y/size);for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const b of grid.get((cx+ox)+','+(cy+oy))||[]){if(a.id>=b.id)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=((a.radius||4)+(b.radius||4))*nodeScale+10,overlap=min-d;if(overlap<=epsilon)continue;maximum=Math.max(maximum,overlap);if(d<.001){const angle=hashAngle(a.id+'|'+b.id);dx=Math.cos(angle);dy=Math.sin(angle);d=1;overlap=min-d}const nx=dx/d,ny=dy/d,ma=Math.max(1,Math.pow((a.radius||4)*nodeScale,2)),mb=Math.max(1,Math.pow((b.radius||4)*nodeScale,2));let wa=a.fx!=null?0:mb/(ma+mb),wb=b.fx!=null?0:ma/(ma+mb);if(wa===0&&wb===0)continue;if(wa===0)wb=1;if(wb===0)wa=1;a.x-=nx*overlap*wa;a.y-=ny*overlap*wa;b.x+=nx*overlap*wb;b.y+=ny*overlap*wb}}if(maximum<=epsilon)break}return maximum}
    function layoutMetrics(visible){if(!visible.length)return{accepted:true,maxOverlap:0,radialRatio:1};const overlap=resolvePositions(visible,2,.02);let cx=0,cy=0;for(const n of visible){cx+=n.x;cy+=n.y}cx/=visible.length;cy/=visible.length;const radial=visible.map(n=>Math.hypot(n.x-cx,n.y-cy)).sort((a,b)=>a-b),p95=radial[Math.max(0,Math.ceil(radial.length*.95)-1)]||1,max=radial[radial.length-1]||0,ratio=max/Math.max(1,p95);return{accepted:overlap<=.25&&ratio<=1.55,maxOverlap:overlap,radialRatio:ratio}}
    function step(project){const visible=nodes.filter(n=>n.visible!==false),map=new Map(visible.map(n=>[n.id,n])),searchMode=searchRoles.size>0,core=searchMode?visible.filter(n=>searchRoles.get(n.id)==='match'):visible,satellites=searchMode?visible.filter(n=>searchRoles.get(n.id)==='context'):[],coreRoot=tree(core),satelliteRoot=satellites.length?tree(satellites):coreRoot,maxR=Math.max(4,...visible.map(n=>(n.radius||4)*nodeScale)),cellSize=Math.max(24,opts.distance*.3,maxR*2+12),grid=new Map();
      let coreX=0,coreY=0;for(const n of core){coreX+=n.x;coreY+=n.y}coreX/=Math.max(1,core.length);coreY/=Math.max(1,core.length);let coreRms=0;for(const n of core)coreRms+=(n.x-coreX)*(n.x-coreX)+(n.y-coreY)*(n.y-coreY);coreRms=Math.sqrt(coreRms/Math.max(1,core.length));const rimRadius=Math.max(opts.distance*2.5,coreRms*1.55+opts.distance*1.15);
      for(const e of edges){const a=map.get(e.source),b=map.get(e.target),ar=searchRoles.get(e.source),br=searchRoles.get(e.target);if(!a||!b||!((ar==='context')!==(br==='context')))continue;const satellite=ar==='context'?a:b,anchor=ar==='context'?b:a,dx=anchor.x-satellite.x,dy=anchor.y-satellite.y,d=Math.hypot(dx,dy)||1,extension=d-opts.distance*3,f=extension*.00115*opts.link*11*alpha;satellite.vx+=dx*f;satellite.vy+=dy*f}
      const familyCenters=new Map(),centerNodes=searchMode?core:visible;for(const n of centerNodes){const family=n.family||('folder:'+n.folder);let f=familyCenters.get(family);if(!f)familyCenters.set(family,f={x:0,y:0,count:0,fx:0,fy:0});f.x+=n.x;f.y+=n.y;f.count++}for(const f of familyCenters.values()){f.x/=f.count;f.y/=f.count}const major=[...familyCenters.values()].filter(f=>f.count>=Math.max(8,centerNodes.length*.008));for(let i=0;i<major.length;i++)for(let j=i+1;j<major.length;j++){const a=major[i],b=major[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,unit=Math.max(8,opts.distance*.06),desired=(Math.sqrt(a.count)+Math.sqrt(b.count))*unit;if(d>=desired)continue;const push=(1-d/desired)*.075*alpha,nx=dx/d,ny=dy/d;a.fx-=nx*push;a.fy-=ny*push;b.fx+=nx*push;b.fy+=ny*push}
      const graphCenter={x:coreX,y:coreY},envelopeRadius=occupiedEnvelope(centerNodes),componentPush=searchMode?new Map():componentForces(centerNodes,graphCenter,envelopeRadius);for(const n of visible){const f=familyCenters.get(n.family||('folder:'+n.folder)),role=searchRoles.get(n.id);if(searchMode&&role==='context'){const dx=n.x-coreX,dy=n.y-coreY,d=Math.hypot(dx,dy)||1,radial=(rimRadius-d)*.012*alpha;n.vx=(n.vx||0)*.72+dx/d*radial;n.vy=(n.vy||0)*.72+dy/d*radial;repel(n,satelliteRoot)}else{const centered=centerForce(n,f||graphCenter,graphCenter,envelopeRadius,opts.center),component=componentPush.get(n.component)||{x:0,y:0};n.vx=(n.vx||0)*.72+alpha*(centered.x+component.x+((f?.x||n.x)-n.x)*.00028)+(f?.fx||0);n.vy=(n.vy||0)*.72+alpha*(centered.y+component.y+((f?.y||n.y)-n.y)*.00028)+(f?.fy||0);repel(n,coreRoot)}const key=Math.floor(n.x/cellSize)+','+Math.floor(n.y/cellSize);if(!grid.has(key))grid.set(key,[]);grid.get(key).push(n)}
      for(const a of visible){const cx=Math.floor(a.x/cellSize),cy=Math.floor(a.y/cellSize);for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const b of grid.get((cx+ox)+','+(cy+oy))||[]){if(a.id>=b.id)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.1,min=((a.radius||4)+(b.radius||4))*nodeScale+10;if(d<min){const f=(min-d)/d*.6*alpha;a.vx-=dx*f;a.vy-=dy*f;b.vx+=dx*f;b.vy+=dy*f}}}
      for(const e of edges){const a=map.get(e.source),b=map.get(e.target);if(!a||!b||(searchMode&&(searchRoles.get(a.id)==='context'||searchRoles.get(b.id)==='context')))continue;const sibling=e.relationship==='sibling',siblingMultiplier=sibling?Math.max(0,opts.siblingLinkForce||0):1;if(siblingMultiplier===0)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,elastic=springExtension(d,opts.distance,opts.stretchiness),normalized=degreeSpring(a.degree||1,b.degree||1),raw=elastic/d*.0046*opts.link*siblingMultiplier*normalized*alpha,f=Math.max(-.65,Math.min(.65,raw));a.vx+=dx*f;a.vy+=dy*f;b.vx-=dx*f;b.vy-=dy*f;const curvatureMagnitude=Math.abs(opts.curvature),curvatureDirection=Math.sign(opts.curvature)||1;if(curvatureMagnitude>0){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2,cx=Math.floor(mx/cellSize),cy=Math.floor(my/cellSize),key=e.source+'\\0'+e.target;for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const n of grid.get((cx+ox)+','+(cy+oy))||[]){if(n===a||n===b)continue;const t=((n.x-a.x)*dx+(n.y-a.y)*dy)/(d*d);if(t<.15||t>.85)continue;const side=((n.x-a.x)*dy-(n.y-a.y)*dx)/d,clear=(n.radius||4)*nodeScale+14;if(Math.abs(side)<clear){let route=routeSides.get(key);if(route==null){route=side>=0?-1:1;routeSides.set(key,route)}const push=(1-Math.abs(side)/clear)*curvatureMagnitude*.2*alpha*route*curvatureDirection,nx=dy/d,ny=-dx/d;a.vx+=nx*push;a.vy+=ny*push;b.vx+=nx*push;b.vy+=ny*push}}}}
      if(Math.abs(opts.curvature)>0&&stepNo++%6===0)separateAngles(map);let energy=0;for(const n of visible){if(n.fx!=null){n.x=n.fx;n.y=n.fy;n.vx=0;n.vy=0;continue}const speed=Math.hypot(n.vx,n.vy);if(speed>8){n.vx=n.vx/speed*8;n.vy=n.vy/speed*8}if(speed<.003){n.vx=0;n.vy=0}n.x+=n.vx;n.y+=n.vy;energy+=n.vx*n.vx+n.vy*n.vy;if(!Number.isFinite(n.x)||Math.abs(n.x)>100000){n.x=0;n.y=0;n.vx=0;n.vy=0}}if(project)resolvePositions(visible,3,.02);return energy/Math.max(1,visible.length)}
  `;
  return new Worker(URL.createObjectURL(new Blob([source], { type: "text/javascript" })));
}
