import { centroidAcceleration, repelFactor } from "./center-force.ts";
import { convergenceDecision, familyComponentIds, linkSpringImpulse, normalizedForceResidual } from "./physics-force.ts";

export function createPhysicsWorkerSource():string {
  const source = `
    const centroidForce=${centroidAcceleration.toString()};
    const repelScale=${repelFactor.toString()};
    const springImpulse=${linkSpringImpulse.toString()};
    const normalizedForceResidual=${normalizedForceResidual.toString()};
    const decideConvergence=${convergenceDecision.toString()};
    const deriveFamilyComponents=${familyComponentIds.toString()};
    let nodes=[],edges=[],opts={center:1.23589544,repel:1,link:.041472,distance:362.874,curvature:0,siblingLinkForce:1};
    let timer,alpha=1,quiet=0,nodeScale=1,routeSides=new Map(),adjacency=new Map(),familyComponentById=new Map(),searchRoles=new Map(),stepNo=0,generation=0,publishStep=0,thoroughRunning=false;
    const byId=()=>new Map(nodes.map(n=>[n.id,n]));
    onmessage=e=>{const m=e.data;
      if(m.type==='init'){
        generation=m.generation||0;nodes=m.nodes.map((n,index)=>({...n,index,vx:0,vy:0,fx:null,fy:null}));edges=m.edges;opts=m.opts;nodeScale=m.nodeScale||1;routeSides=new Map();rebuildTopology();stepNo=0;publishStep=0;
        const heat=m.heat??1;if(heat>0)run(heat,m.thorough!==false);else publish('settled');
      }else if(m.type==='forces'){opts=m.opts;if(m.thorough&&thoroughRunning)publish('analysisRunning',{thorough:true});else run(1,!!m.thorough)}
      else if(m.type==='searchRoles'){searchRoles=new Map(m.roles);run(.75)}
      else if(m.type==='nodeScale'){
        nodeScale=Math.max(.01,m.value||1);const visible=nodes.filter(n=>n.visible!==false),passes=m.final?24:4,epsilon=Math.max(0,m.epsilonWorld||0);resolvePositions(visible,passes,epsilon);for(const n of visible){n.vx=0;n.vy=0}publish('projection',{scaleGeneration:m.scaleGeneration||0});
      }else if(m.type==='dragStart'){const n=byId().get(m.id);if(n){n.fx=m.x;n.fy=m.y;n.x=m.x;n.y=m.y;n.vx=0;n.vy=0;run(.65)}}
      else if(m.type==='dragMove'){const n=byId().get(m.id);if(n){n.fx=m.x;n.fy=m.y;n.x=m.x;n.y=m.y;n.vx=0;n.vy=0;if(!timer)run(.45);else alpha=Math.max(alpha,.35)}}
      else if(m.type==='dragEnd'){const n=byId().get(m.id);if(n){n.fx=null;n.fy=null;run(.35)}}
    };
    function publish(type,extra={}){const coords=new Float32Array(nodes.length*2);for(const n of nodes){coords[n.index*2]=n.x;coords[n.index*2+1]=n.y}postMessage({type,generation,coords,...extra},[coords.buffer])}
    function run(heat,thorough=false){alpha=Math.max(alpha,heat);quiet=0;if(timer)clearInterval(timer);thoroughRunning=thorough;let cycles=0,lastEnergy=Infinity,lastAlpha=alpha;const substeps=thorough?6:2,decay=thorough?.978:.96,minAlpha=thorough?.006:.02,maxCycles=thorough?6:1;timer=setInterval(()=>{let energy=0;for(let i=0;i<substeps;i++)energy=step(i===substeps-1);lastEnergy=energy;lastAlpha=alpha;if(publishStep++%2===0)publish('tick',{thorough});alpha*=decay;if(alpha<minAlpha&&energy<(thorough?.003:.008)){quiet++;if(quiet>(thorough?28:18)){const metrics=layoutMetrics(nodes.filter(n=>n.visible!==false),lastEnergy,lastAlpha,thorough,cycles,maxCycles);if(metrics.state==='settled'){clearInterval(timer);timer=undefined;thoroughRunning=false;publish('settled',{metrics,thorough})}else if(metrics.state==='reheat'){cycles++;alpha=thorough?.45:.12;quiet=0;publish('preview',{metrics,thorough,cycle:cycles})}else{clearInterval(timer);timer=undefined;thoroughRunning=false;publish('incomplete',{metrics,thorough,cycles})}}}else quiet=0},16)}
    function rebuildTopology(){adjacency=new Map(nodes.map(n=>[n.id,[]]));for(const e of edges){if(adjacency.has(e.source)&&adjacency.has(e.target)){adjacency.get(e.source).push(e.target);adjacency.get(e.target).push(e.source)}}familyComponentById=deriveFamilyComponents(nodes,edges)}
    function hashAngle(value){let h=2166136261;for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619);return((h>>>0)/4294967296)*Math.PI*2}
    function tree(points){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const n of points){minX=Math.min(minX,n.x);minY=Math.min(minY,n.y);maxX=Math.max(maxX,n.x);maxY=Math.max(maxY,n.y)}if(!points.length)return{x:0,y:0,size:1,items:[],kids:null,cx:0,cy:0,count:0};const size=Math.max(1,maxX-minX,maxY-minY),root={x:minX,y:minY,size,items:[],kids:null,cx:0,cy:0,count:0};function insert(q,n,depth){q.count++;q.cx+=(n.x-q.cx)/q.count;q.cy+=(n.y-q.cy)/q.count;if(!q.kids&&(q.items.length<4||depth>16)){q.items.push(n);return}if(!q.kids){q.kids=[0,1,2,3].map(i=>({x:q.x+(i%2)*q.size/2,y:q.y+(i>1?q.size/2:0),size:q.size/2,items:[],kids:null,cx:0,cy:0,count:0}));for(const old of q.items)insert(q.kids[(old.x>=q.x+q.size/2?1:0)+(old.y>=q.y+q.size/2?2:0)],old,depth+1);q.items=[]}insert(q.kids[(n.x>=q.x+q.size/2?1:0)+(n.y>=q.y+q.size/2?2:0)],n,depth+1)}for(const n of points)insert(root,n,0);return root}
    function repel(n,q){if(!q.count)return;const dx=q.cx-n.x,dy=q.cy-n.y,d2=dx*dx+dy*dy+.01;if(!q.kids){for(const b of q.items){if(b===n)continue;const x=b.x-n.x,y=b.y-n.y,r2=x*x+y*y+36,f=repelScale(r2,1,opts.repel,alpha);n.vx-=x*f;n.vy-=y*f}return}if(q.size*q.size/d2<.55){const f=repelScale(d2,q.count,opts.repel,alpha);n.vx-=dx*f;n.vy-=dy*f;return}for(const k of q.kids)repel(n,k)}
    function separateAngles(map){const magnitude=Math.abs(opts.curvature),direction=Math.sign(opts.curvature)||1;for(const [id,ids] of adjacency){const hub=map.get(id);if(!hub||ids.length<2)continue;const ns=ids.map(x=>map.get(x)).filter(Boolean).map(n=>({n,a:Math.atan2(n.y-hub.y,n.x-hub.x)})).sort((a,b)=>a.a-b.a),desired=Math.min(.7,Math.PI*2/ns.length);for(let i=0;i<ns.length;i++){const left=ns[i],right=ns[(i+1)%ns.length],gap=((right.a-left.a+Math.PI*2)%(Math.PI*2));if(gap>=desired)continue;const push=(desired-gap)*magnitude*.055*alpha*direction,la=left.a,ra=right.a;left.n.vx+=Math.sin(la)*push;left.n.vy-=Math.cos(la)*push;right.n.vx-=Math.sin(ra)*push;right.n.vy+=Math.cos(ra)*push}}}
    function resolvePositions(visible,passes=3,epsilon=0){const maxR=Math.max(4,...visible.map(n=>(n.radius||4)*nodeScale)),size=maxR*2+12;let maximum=0;for(let pass=0;pass<passes;pass++){maximum=0;const grid=new Map();for(const n of visible){const key=Math.floor(n.x/size)+','+Math.floor(n.y/size);if(!grid.has(key))grid.set(key,[]);grid.get(key).push(n)}for(const a of visible){const cx=Math.floor(a.x/size),cy=Math.floor(a.y/size);for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const b of grid.get((cx+ox)+','+(cy+oy))||[]){if(a.id>=b.id)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=((a.radius||4)+(b.radius||4))*nodeScale+10,overlap=min-d;if(overlap<=epsilon)continue;maximum=Math.max(maximum,overlap);if(d<.001){const angle=hashAngle(a.id+'|'+b.id);dx=Math.cos(angle);dy=Math.sin(angle);d=1;overlap=min-d}const nx=dx/d,ny=dy/d,ma=Math.max(1,Math.pow((a.radius||4)*nodeScale,2)),mb=Math.max(1,Math.pow((b.radius||4)*nodeScale,2));let wa=a.fx!=null?0:mb/(ma+mb),wb=b.fx!=null?0:ma/(ma+mb);if(wa===0&&wb===0)continue;if(wa===0)wb=1;if(wb===0)wa=1;a.x-=nx*overlap*wa;a.y-=ny*overlap*wa;b.x+=nx*overlap*wb;b.y+=ny*overlap*wb}}if(maximum<=epsilon)break}return maximum}
    function layoutMetrics(visible,energy,currentAlpha,thorough,cycle,maxCycles){const overlap=resolvePositions(visible,2,.02),decision=decideConvergence(overlap,energy,currentAlpha,thorough,cycle,maxCycles);return{state:decision.state,maxOverlap:overlap,forceResidual:decision.residual}}
    function step(project){const visible=nodes.filter(n=>n.visible!==false),map=new Map(visible.map(n=>[n.id,n])),searchMode=searchRoles.size>0,core=searchMode?visible.filter(n=>searchRoles.get(n.id)==='match'):visible,satellites=searchMode?visible.filter(n=>searchRoles.get(n.id)==='context'):[],coreRoot=tree(core),satelliteRoot=satellites.length?tree(satellites):coreRoot,maxR=Math.max(4,...visible.map(n=>(n.radius||4)*nodeScale)),cellSize=Math.max(24,opts.distance*.3,maxR*2+12),grid=new Map();
      let coreX=0,coreY=0;for(const n of core){coreX+=n.x;coreY+=n.y}coreX/=Math.max(1,core.length);coreY/=Math.max(1,core.length);
      for(const e of edges){const a=map.get(e.source),b=map.get(e.target),ar=searchRoles.get(e.source),br=searchRoles.get(e.target);if(!a||!b||!((ar==='context')!==(br==='context')))continue;const satellite=ar==='context'?a:b,anchor=ar==='context'?b:a,dx=anchor.x-satellite.x,dy=anchor.y-satellite.y,d=Math.hypot(dx,dy)||1,magnitude=Math.max(-8,Math.min(8,(d-opts.distance*3)*.8*opts.link*11*alpha));satellite.vx+=dx/d*magnitude;satellite.vy+=dy/d*magnitude}
      const familyCenters=new Map(),componentCenters=new Map(),centerNodes=searchMode?core:visible;for(const n of centerNodes){const family=n.family||('folder:'+n.folder);let f=familyCenters.get(family);if(!f)familyCenters.set(family,f={x:0,y:0,count:0,fx:0,fy:0});f.x+=n.x;f.y+=n.y;f.count++;const component=familyComponentById.get(n.id)??n.id;let c=componentCenters.get(component);if(!c)componentCenters.set(component,c={x:0,y:0,count:0,family});c.x+=n.x;c.y+=n.y;c.count++}for(const f of familyCenters.values()){f.x/=f.count;f.y/=f.count}for(const c of componentCenters.values()){c.x/=c.count;c.y/=c.count}const major=[...familyCenters.values()].filter(f=>f.count>=Math.max(8,centerNodes.length*.008));for(let i=0;i<major.length;i++)for(let j=i+1;j<major.length;j++){const a=major[i],b=major[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,unit=Math.max(8,opts.distance*.06),desired=(Math.sqrt(a.count)+Math.sqrt(b.count))*unit;if(d>=desired)continue;const push=(1-d/desired)*.075*alpha,nx=dx/d,ny=dy/d;a.fx-=nx*push;a.fy-=ny*push;b.fx+=nx*push;b.fy+=ny*push}
      const graphCenter={x:coreX,y:coreY};for(const n of visible){const f=familyCenters.get(n.family||('folder:'+n.folder)),component=componentCenters.get(familyComponentById.get(n.id)??n.id),role=searchRoles.get(n.id);if(searchMode&&role==='context'){n.vx=(n.vx||0)*.72;n.vy=(n.vy||0)*.72;repel(n,satelliteRoot)}else{const familyPull=centroidForce(f||graphCenter,graphCenter,opts.center,.0025),componentPull=centroidForce(component||f||graphCenter,f||graphCenter,opts.center,.0012);n.vx=(n.vx||0)*.72+alpha*(familyPull.x+componentPull.x)+(f?.fx||0);n.vy=(n.vy||0)*.72+alpha*(familyPull.y+componentPull.y)+(f?.fy||0);repel(n,coreRoot)}const key=Math.floor(n.x/cellSize)+','+Math.floor(n.y/cellSize);if(!grid.has(key))grid.set(key,[]);grid.get(key).push(n)}
      for(const a of visible){const cx=Math.floor(a.x/cellSize),cy=Math.floor(a.y/cellSize);for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const b of grid.get((cx+ox)+','+(cy+oy))||[]){if(a.id>=b.id)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.1,min=((a.radius||4)+(b.radius||4))*nodeScale+10;if(d<min){const f=(min-d)/d*.6*alpha;a.vx-=dx*f;a.vy-=dy*f;b.vx+=dx*f;b.vy+=dy*f}}}
      for(const e of edges){const a=map.get(e.source),b=map.get(e.target);if(!a||!b||(searchMode&&(searchRoles.get(a.id)==='context'||searchRoles.get(b.id)==='context')))continue;const sibling=e.relationship==='sibling',siblingMultiplier=sibling?Math.max(0,opts.siblingLinkForce||0):1;if(siblingMultiplier===0)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1,impulse=springImpulse(a,b,opts.distance,opts.link,siblingMultiplier,alpha);a.vx+=impulse.source.x;a.vy+=impulse.source.y;b.vx+=impulse.target.x;b.vy+=impulse.target.y;const curvatureMagnitude=Math.abs(opts.curvature),curvatureDirection=Math.sign(opts.curvature)||1;if(curvatureMagnitude>0){const mx=(a.x+b.x)/2,my=(a.y+b.y)/2,cx=Math.floor(mx/cellSize),cy=Math.floor(my/cellSize),key=e.source+'\\0'+e.target;for(let ox=-1;ox<=1;ox++)for(let oy=-1;oy<=1;oy++)for(const n of grid.get((cx+ox)+','+(cy+oy))||[]){if(n===a||n===b)continue;const t=((n.x-a.x)*dx+(n.y-a.y)*dy)/(d*d);if(t<.15||t>.85)continue;const side=((n.x-a.x)*dy-(n.y-a.y)*dx)/d,clear=(n.radius||4)*nodeScale+14;if(Math.abs(side)<clear){let route=routeSides.get(key);if(route==null){route=side>=0?-1:1;routeSides.set(key,route)}const push=(1-Math.abs(side)/clear)*curvatureMagnitude*.2*alpha*route*curvatureDirection,nx=dy/d,ny=-dx/d;a.vx+=nx*push;a.vy+=ny*push;b.vx+=nx*push;b.vy+=ny*push}}}}
      if(Math.abs(opts.curvature)>0&&stepNo++%6===0)separateAngles(map);let energy=0;for(const n of visible){if(n.fx!=null){n.x=n.fx;n.y=n.fy;n.vx=0;n.vy=0;continue}const speed=Math.hypot(n.vx,n.vy);if(speed>8){n.vx=n.vx/speed*8;n.vy=n.vy/speed*8}if(speed<.003){n.vx=0;n.vy=0}n.x+=n.vx;n.y+=n.vy;energy+=n.vx*n.vx+n.vy*n.vy;if(!Number.isFinite(n.x)||Math.abs(n.x)>100000){n.x=0;n.y=0;n.vx=0;n.vy=0}}if(project)resolvePositions(visible,3,.02);return energy/Math.max(1,visible.length)}
  `;
  return source;
}

export function createPhysicsWorker(): Worker {
  return new Worker(URL.createObjectURL(new Blob([createPhysicsWorkerSource()], { type: "text/javascript" })));
}
