import {JavaScriptSimulationEngine} from "./javascript-simulation-engine.ts";
import {SharedCoordinateWriter} from "./coordinate-transport.ts";
import type {SimulationEngine} from "./simulation-contract.ts";
import {ALPHA_DECAY,ALPHA_INITIAL,ALPHA_MIN,ALPHA_TARGET_REST,AUTOMATIC_WAKE_ALPHA,DRAG_ALPHA_TARGET,WORKER_PROTOCOL_VERSION,WORKER_TICK_INTERVAL_MS,alphaDecayForTicks,isGraphWorkerRequest,type GraphWorkerRequest,type GraphWorkerResponse} from "./worker-protocol.ts";

export type WorkerRuntimeDependencies={post:(message:GraphWorkerResponse,transfer?:Transferable[])=>void;setTimer:(callback:()=>void,delay:number)=>unknown;clearTimer:(timer:unknown)=>void;createEngine?:()=>SimulationEngine|Promise<SimulationEngine>;supportsSharedMemory?:()=>boolean};

export function createGraphWorkerRuntime(deps:WorkerRuntimeDependencies){
  let engine:SimulationEngine|undefined,revision=0,alpha=ALPHA_INITIAL,alphaTarget=ALPHA_TARGET_REST,alphaDecay=ALPHA_DECAY,warmupTicks=0,warmupCoolingTicks=0,timer:unknown,disposed=false,initializing=false,serial=0,pending:GraphWorkerRequest[]=[],sharedEnabled=(deps.supportsSharedMemory?.()??typeof SharedArrayBuffer!=="undefined"),sharedWriter:SharedCoordinateWriter|undefined,publishedRevision=-1,lastTickMs=0;
  const publish=(type:"coordinates"|"sleep")=>{if(!engine)return;const state=engine.snapshot(),orderChanged=publishedRevision!==revision,metrics={tickMs:lastTickMs,...engine.memoryUsage()};if(sharedEnabled){try{sharedWriter??=new SharedCoordinateWriter();const resized=sharedWriter.ensureCapacity(state.length),publication=sharedWriter.publishPoints(state);deps.post({type,version:WORKER_PROTOCOL_VERSION,revision,transport:"shared",publication:publication.publication,count:publication.count,ids:orderChanged?state.map(node=>node.id):undefined,buffer:resized?publication.buffer:undefined,alpha,metrics});publishedRevision=revision;return}catch{sharedEnabled=false;sharedWriter=undefined}}const ids=state.map(node=>node.id),coords=new Float32Array(state.length*2);for(let index=0;index<state.length;index++){const node=state[index]!;coords[index*2]=node.x;coords[index*2+1]=node.y}deps.post({type,version:WORKER_PROTOCOL_VERSION,revision,transport:"transfer",ids,coords,alpha,metrics},[coords.buffer])};
  const cancel=()=>{if(timer!==undefined)deps.clearTimer(timer);timer=undefined};
  const shouldRun=()=>!disposed&&!initializing&&!!engine&&(alpha>=ALPHA_MIN||alphaTarget>=ALPHA_MIN);
  const schedule=()=>{if(timer===undefined&&shouldRun())timer=deps.setTimer(run,WORKER_TICK_INTERVAL_MS)};
  const wake=(requested=AUTOMATIC_WAKE_ALPHA)=>{if(Number.isFinite(requested)&&requested>alpha)alpha=requested;schedule()};
  const useCoolingBudget=(ticks?:number)=>{alphaDecay=typeof ticks==="number"&&Number.isFinite(ticks)&&ticks>0?alphaDecayForTicks(Math.max(1,Math.round(ticks))):ALPHA_DECAY};
  const finishInit=(selected:SimulationEngine,message:Extract<GraphWorkerRequest,{type:"init"}>,token:number)=>{if(disposed||token!==serial){selected.dispose();return}engine=selected;engine.updateForces(message.forces);engine.reconcile(message.nodes,message.edges);initializing=false;deps.post({type:"ready",version:WORKER_PROTOCOL_VERSION,revision,engine:engine.kind});publish("coordinates");wake(message.heat??ALPHA_INITIAL);const queued=pending;pending=[];for(const item of queued)handle(item)};
  const fail=(error:unknown)=>{initializing=false;deps.post({type:"failure",version:WORKER_PROTOCOL_VERSION,message:error instanceof Error?error.message:"Graph simulation engine initialization failed."})};
  const initialize=(message:Extract<GraphWorkerRequest,{type:"init"}>)=>{cancel();engine?.dispose();engine=undefined;pending=[];revision=message.revision;publishedRevision=-1;alpha=ALPHA_INITIAL;alphaTarget=ALPHA_TARGET_REST;warmupTicks=0;warmupCoolingTicks=0;useCoolingBudget(message.coolingTicks);initializing=true;const token=++serial;try{const selected=deps.createEngine?.()??new JavaScriptSimulationEngine();if(selected instanceof Promise)void selected.then(value=>finishInit(value,message,token)).catch(fail);else finishInit(selected,message,token)}catch(error){fail(error)}};
  const useNormalCooling=()=>{warmupTicks=0;warmupCoolingTicks=0;alphaDecay=ALPHA_DECAY};
  const tick=()=>{if(!engine)return;if(warmupTicks>0){warmupTicks--;alpha+=(DRAG_ALPHA_TARGET-alpha)*ALPHA_DECAY;if(warmupTicks===0&&warmupCoolingTicks>0)alphaDecay=1-Math.pow(ALPHA_MIN/Math.max(ALPHA_MIN,alpha),1/warmupCoolingTicks)}else alpha+=(alphaTarget-alpha)*alphaDecay;const started=performance.now();engine.tick(alpha);lastTickMs=performance.now()-started};
  function run(){timer=undefined;if(!shouldRun())return;timer=deps.setTimer(run,WORKER_TICK_INTERVAL_MS);try{tick();publish("coordinates")}catch(error){cancel();disposed=true;deps.post({type:"failure",version:WORKER_PROTOCOL_VERSION,message:error instanceof Error?error.message:"Graph simulation failed."});return}if(!shouldRun()){cancel();publish("sleep");useNormalCooling()}}
  const handle=(message:GraphWorkerRequest)=>{
    if(disposed)return;if(message.type==="dispose"){disposed=true;serial++;pending=[];cancel();engine?.dispose();engine=undefined;return}if(message.type==="init"){initialize(message);return}if(initializing){pending.push(message);return}if(!engine)return;
    if(message.type==="topology"){useCoolingBudget(message.coolingTicks);warmupTicks=Math.max(0,Math.round(message.warmupTicks??0));warmupCoolingTicks=message.coolingTicks??0;revision=message.revision;engine.reconcile(message.nodes,message.edges);wake(message.heat);return}if(message.type==="forces"){useNormalCooling();engine.updateForces(message.forces);wake(message.heat);return}if(message.type==="weights"){useNormalCooling();engine.updateWeights(message.weights);wake(message.heat);return}
    useNormalCooling();if(message.type==="dragEnd"){engine.setPin(message.id,null,null);alphaTarget=ALPHA_TARGET_REST;wake(AUTOMATIC_WAKE_ALPHA);return}engine.setPin(message.id,message.x,message.y);alphaTarget=DRAG_ALPHA_TARGET;wake(DRAG_ALPHA_TARGET);publish("coordinates");
  };
  return{onMessage:(value:unknown)=>{if(!isGraphWorkerRequest(value)){deps.post({type:"failure",version:WORKER_PROTOCOL_VERSION,message:"Unsupported graph worker protocol message."});return}try{handle(value)}catch(error){cancel();deps.post({type:"failure",version:WORKER_PROTOCOL_VERSION,message:error instanceof Error?error.message:"Graph simulation message failed."})}},dispose:()=>handle({type:"dispose",version:WORKER_PROTOCOL_VERSION}),inspect:()=>({alpha,alphaTarget,scheduled:timer!==undefined,revision,nodeIds:engine?.snapshot().map(node=>node.id)??[],engine:engine?.kind})};
}
